'use client';
import { useEffect, useMemo, useState } from 'react';
import { Activity, ChevronRight, Command, Gauge, GitBranch, Globe2, Lock, MessageSquare, Package, RefreshCw, Rocket, Settings2, ShieldCheck, Store, Wallet } from 'lucide-react';
const API='/api/nexus';
type Project={id:string;name:string;repo?:string};
type Deployment={id:string;status:string;project:string;createdAt:string};
type Gate={id:string;name:string;kind:string;required:boolean};
type Metric={metric:string;unit:string;quantity:string|number};
type Provider={id:string;name:string;category:string;description:string;capabilities:string[]};
async function get<T>(p:string,o?:RequestInit){const r=await fetch(API+p,{...o,credentials:'include',headers:{'content-type':'application/json',...(o?.headers||{})}});const v=await r.json().catch(()=>({}));if(!r.ok)throw new Error(v.error||v.detail||`HTTP ${r.status}`);return v as T;}
export default function Dashboard(){const [projects,setProjects]=useState<Project[]>([]);const [projectId,setProjectId]=useState('');const [deployments,setDeployments]=useState<Deployment[]>([]);const [gates,setGates]=useState<Gate[]>([]);const [metrics,setMetrics]=useState<Metric[]>([]);const [providers,setProviders]=useState<Provider[]>([]);const [policy,setPolicy]=useState<any>();const [settings,setSettings]=useState<any>();const [selected,setSelected]=useState<any>();const [comment,setComment]=useState('');const [tab,setTab]=useState('overview');const [notice,setNotice]=useState('');
const project=useMemo(()=>projects.find(p=>p.id===projectId),[projects,projectId]);
async function load(){try{const [p,d]=await Promise.all([get<Project[]>('/v1/projects'),get<Deployment[]>('/v1/deployments')]);setProjects(p);setDeployments(d);if(!projectId&&p[0])setProjectId(p[0].id);}catch(e){setNotice(e instanceof Error?e.message:'Unable to load dashboard');}}
async function loadProject(id:string){if(!id)return;try{const [g,m,pp,s]=await Promise.all([get<{gates:Gate[]}>(`/v1/projects/${id}/release-gates`),get<{usage:Metric[];deployments:any[];incidents:any[]}>(`/v1/projects/${id}/metrics`),get<any>(`/v1/projects/${id}/preview-policy`),get<any>(`/v1/projects/${id}/settings`)]);setGates(g.gates);setMetrics(m.usage);setPolicy(pp.policy);setSettings(s.settings);}catch(e){setNotice(e instanceof Error?e.message:'Project data unavailable');}}
useEffect(()=>{load();get<{providers:Provider[]}>('/v1/providers/catalog').then(x=>setProviders(x.providers)).catch(()=>{});},[]);useEffect(()=>{loadProject(projectId);},[projectId]);
async function inspector(id:string){try{setSelected(await get<any>(`/v1/deployments/${id}/inspector`));setTab('inspector');}catch(e){setNotice(e instanceof Error?e.message:'Inspector unavailable');}}
async function savePolicy(mode:string){try{const x=await get<any>(`/v1/projects/${projectId}/preview-policy`,{method:'PUT',body:JSON.stringify({mode,requireAuth:mode!=='public',expiresHours:72})});setPolicy(x.policy);setNotice('Preview protection updated.');}catch(e){setNotice(e instanceof Error?e.message:'Policy update failed');}}
async function addGate(){try{const x=await get<any>(`/v1/projects/${projectId}/release-gates`,{method:'PUT',body:JSON.stringify({name:`health-${Date.now()}`,kind:'health',required:true,config:{timeoutSeconds:120}})});setGates(v=>[...v.filter(g=>g.name!==x.gate.name),x.gate]);setNotice('Release gate saved.');}catch(e){setNotice(e instanceof Error?e.message:'Gate update failed');}}
async function saveSettings(){try{const x=await get<any>(`/v1/projects/${projectId}/settings`,{method:'PUT',body:JSON.stringify(settings)});setSettings(x.settings);setNotice('Project settings saved.');}catch(e){setNotice(e instanceof Error?e.message:'Settings update failed');}}
async function addComment(){if(!selected||!comment.trim())return;try{const x=await get<any>(`/v1/deployments/${selected.id}/comments`,{method:'POST',body:JSON.stringify({body:comment})});setSelected((v:any)=>({...v,comments:[...(v.comments||[]),x]}));setComment('');}catch(e){setNotice(e instanceof Error?e.message:'Comment failed');}}
const nav=[['overview','Overview',Gauge],['deployments','Deployments',Rocket],['inspector','Inspector',Activity],['gates','Release Gates',ShieldCheck],['preview','Preview Protection',Lock],['metrics','Metrics',Activity],['billing','Usage & Billing',Wallet],['settings','Settings',Settings2],['providers','Providers',Store]] as const;
return <main className="platformPage"><header className="platformHeader"><div><span className="eyebrow">NEXUS / PROJECT CONSOLE</span><h1>{project?.name||'Project dashboard'}</h1><p>Production-grade deployments, previews, observability and release controls in one workspace.</p></div><div style={{display:'flex',gap:8}}><select className="wideSelect" value={projectId} onChange={e=>setProjectId(e.target.value)}>{projects.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select><button className="mini" onClick={load}><RefreshCw size={15}/> Refresh</button></div></header>
{notice&&<div className="platformNotice"><ShieldCheck size={17}/><span>{notice}</span><button onClick={()=>setNotice('')}>×</button></div>}
<div className="platformTabs">{nav.map(([id,label,I])=><button key={id} className={tab===id?'active':''} onClick={()=>setTab(id)}><I size={14}/>{label}</button>)}</div>
{tab==='overview'&&<section className="platformGrid"><Card title="Production" icon={<Globe2 size={18}/>}><b className="big">{deployments.filter(d=>d.status==='healthy'||d.status==='HEALTHY').length}</b><span>healthy deployments</span><small>Health-gated traffic handoff is handled by the runtime.</small></Card><Card title="Release safety" icon={<ShieldCheck size={18}/>}><b className="big">{gates.length}</b><span>configured gates</span><small>Required checks can block promotion.</small></Card><Card title="Previews" icon={<GitBranch size={18}/>}><b className="big">{policy?.mode||'team'}</b><span>access policy</span><small>Public, team-only or protected preview access.</small></Card><Card title="Runtime" icon={<Package size={18}/>}><b className="big">{providers.length}</b><span>provider adapters</span><small>Portable Docker runtime plus provider contracts.</small></Card></section>}
{tab==='deployments'&&<List title="Deployments">{deployments.filter(d=>!project||d.project===project.name).map(d=><button className="platformRow" key={d.id} onClick={()=>inspector(d.id)}><span><b>{d.project}</b><small>{d.id.slice(0,12)} · {new Date(d.createdAt).toLocaleString()}</small></span><span className={`pill ${d.status.toLowerCase()}`}>{d.status}<ChevronRight size={14}/></span></button>)}</List>}
{tab==='inspector'&&<section className="platformCard full"><div className="cardHead"><div><span className="eyebrow">DEPLOYMENT INSPECTOR</span><h2>{selected?.id?selected.id.slice(0,18):'Select a deployment'}</h2></div></div>{selected?<><div className="usageGrid"><div><b>{selected.status}</b><span>state</span></div><div><b>{selected.serviceName}</b><span>service</span></div><div><b>{selected.environment}</b><span>environment</span></div><div><b>{selected.health?.status}</b><span>health</span></div></div><h3>Release timeline</h3><div className="table">{(selected.events||[]).map((e:any)=><div className="platformRow" key={e.id}><span><b>{e.phase}</b><small>{e.message}</small></span><span>{new Date(e.createdAt).toLocaleTimeString()}</span></div>)}</div><h3>Comments</h3><div className="commentBox"><input value={comment} onChange={e=>setComment(e.target.value)} placeholder="Comment on this deployment…"/><button className="mini" onClick={addComment}><MessageSquare size={14}/> Add</button></div>{(selected.comments||[]).map((c:any)=><p key={c.id}><b>{c.name||c.email||'User'}:</b> {c.body}</p>)}</>:<p className="empty">Open a deployment from the Deployments tab.</p>}</section>}
{tab==='gates'&&<List title="Release gates"><button className="mini" onClick={addGate}><ShieldCheck size={14}/> Add health gate</button>{gates.map(g=><div className="platformRow" key={g.id}><span><b>{g.name}</b><small>{g.kind}</small></span><span className="pill">{g.required?'required':'optional'}</span></div>)}{!gates.length&&<p className="empty">No gates configured. Add one to protect production promotion.</p>}</List>}
{tab==='preview'&&<section className="platformCard full"><span className="eyebrow">PREVIEW ACCESS</span><h2>Preview Protection</h2><p className="muted">Control who can open preview deployments without changing application code.</p><div className="quickActions">{['public','team','protected'].map(m=><button key={m} className={policy?.mode===m?'selected':''} onClick={()=>savePolicy(m)}><Lock size={14}/>{m}</button>)}</div><div className="securityCallout"><Lock size={22}/><div><b>{policy?.mode||'team'} previews</b><span>{policy?.requireAuth?'Authentication required.':'Publicly accessible previews.'} Expiry: {policy?.expiresHours||72}h.</span></div></div></section>}
{tab==='metrics'&&<List title="Project metrics">{metrics.map(m=><div className="platformRow" key={`${m.metric}-${m.unit}`}><span><b>{m.metric}</b><small>{m.unit}</small></span><strong>{m.quantity}</strong></div>)}{!metrics.length&&<p className="empty">Usage events will appear here as runtime services report metering.</p>}</List>}
{tab==='billing'&&<section className="platformCard full"><span className="eyebrow">MONTHLY METERING</span><h2>Usage & billing</h2><div className="securityCallout"><Wallet size={22}/><div><b>Provider-aware billing</b><span>Nexus exposes measured usage but never fabricates provider prices. Connect provider metering before charging users.</span></div></div><div className="table">{metrics.map(m=><div className="platformRow" key={m.metric}><span><b>{m.metric}</b><small>{m.unit}</small></span><span>metered</span></div>)}</div></section>}
{tab==='settings'&&<section className="platformCard full"><span className="eyebrow">PROJECT SETTINGS</span><h2>Deployment behavior</h2><label>Release strategy<select value={settings?.deployment?.strategy||'rolling'} onChange={e=>setSettings({...settings,deployment:{...settings?.deployment,strategy:e.target.value}})}><option>rolling</option><option>blue_green</option><option>canary</option></select></label><label><input type="checkbox" checked={settings?.deployment?.zeroDowntime!==false} onChange={e=>setSettings({...settings,deployment:{...settings?.deployment,zeroDowntime:e.target.checked}})}/> Zero-downtime promotion</label><label><input type="checkbox" checked={settings?.deployment?.rollbackOnFailure!==false} onChange={e=>setSettings({...settings,deployment:{...settings?.deployment,rollbackOnFailure:e.target.checked}})}/> Roll back on failure</label><button className="deployAction" onClick={saveSettings}>Save settings</button></section>}
{tab==='providers'&&<List title="Provider marketplace">{providers.map(p=><div className="platformRow" key={p.id}><span><b>{p.name}</b><small>{p.category} · {p.description}</small></span><span className="pill">{p.capabilities?.join(' · ')}</span></div>)}</List>}
<div className="commandHint"><Command size={14}/> Command palette-ready console · use the project navigation above for every control-plane operation.</div>
</main>}
function Card({title,icon,children}:{title:string;icon:React.ReactNode;children:React.ReactNode}){return <article className="platformCard"><div className="cardHead"><h2>{icon} {title}</h2></div><div className="metricStack">{children}</div></article>}
function List({title,children}:{title:string;children:React.ReactNode}){return <section className="platformCard full"><div className="cardHead"><h2>{title}</h2></div><div className="table">{children}</div></section>}
