'use client';

const areas = [
  ['Deployment runtime','Strong','Validate multiple production providers'],['Queue / worker','Implemented','Failure, restart and node-loss drills'],['GitHub integration','Foundation','GitHub App installation and org UX'],['Preview environments','Foundation','Automatic expiry and garbage collection'],['Domains / TLS','Implemented','Renewal and failure monitoring'],['Tenant isolation','Foundation','Cross-tenant authorization and runtime tests'],['Abuse protection','Required','Rate limits, quotas and runtime guardrails'],['Billing','Metering','Subscriptions, invoices and payment provider adapter'],['PostgreSQL','Foundation','Automated backups and verified restore'],['Disaster recovery','Foundation','Scheduled drills with RTO/RPO evidence'],['Notifications','Foundation','Email, signed webhooks and ChatOps'],['Artifact registry','Foundation','Immutable digest-addressed production artifacts'],['SLOs','Foundation','Availability, latency and error-budget monitoring'],['Support','Foundation','Tickets, incident process and status communication']
] as const;

export default function GACenter(){
 return <main className="platformPage"><header className="platformHeader"><div><a href="/platform" className="backLink">← Control plane</a><span className="eyebrow">NEXUS / GENERAL AVAILABILITY</span><h1>Launch control center</h1><p>One clean operational view for the capabilities required before Nexus accepts production customers.</p></div><a className="mini" href="/platform/releases">Release safety →</a></header>
 <section className="gaHero"><div><span className="eyebrow">PRODUCT GATE</span><h2>Evidence before launch</h2><p>Every area has an implementation state and a concrete production proof requirement. Nothing is marked GA merely because a database table exists.</p></div><div className="gaScore"><strong>{areas.filter(a=>a[1]==='Implemented'||a[1]==='Strong').length}/{areas.length}</strong><span>operationally strong areas</span></div></section>
 <section className="gaGrid">{areas.map(([name,state,next])=><article className={`gaCard ${state.toLowerCase().replaceAll(' ','-')}`} key={name}><div className="gaCardTop"><span>{state}</span><b>{name}</b></div><p>{next}</p></article>)}</section>
 <section className="platformCard full"><div className="cardHead"><div><span className="eyebrow">LAUNCH ORDER</span><h2>Beta → GA</h2></div></div><div className="gaSteps"><div><b>01</b><strong>Security</strong><span>Tenant isolation, SSRF/runtime boundaries and abuse controls.</span></div><div><b>02</b><strong>Reliability</strong><span>Backup restore, worker recovery, provider validation and DR drills.</span></div><div><b>03</b><strong>Commercial</strong><span>Plans, subscription state, invoices, metering and payment adapter.</span></div><div><b>04</b><strong>Operations</strong><span>SLOs, alerts, support workflow, incident evidence and status.</span></div></div></section>
 </main>;
}
