'use client';
import { useEffect, useState } from 'react';
import { Activity, ArrowUpRight, Boxes, Database, Globe2, GitBranch, Rocket, ShieldCheck, Sparkles, Terminal, Zap, X } from 'lucide-react';

const API=process.env.NEXT_PUBLIC_NEXUS_API_URL??'http://localhost:4000';
const services=[['Web Service','Frontend, API and full-stack applications.','Globe2'],['Worker','Background jobs and long-running consumers.','Boxes'],['Private Service','Internal APIs and service-to-service workloads.','ShieldCheck'],['Database','Connect PostgreSQL, Redis and external data services.','Database']];
type Deployment={id:string;status:string;repo?:string;runtime?:{url?:string;host?:string;tls?:boolean};createdAt:string};

export default function Home(){
 const [open,setOpen]=useState(false); const [busy,setBusy]=useState(false); const [deployed,setDeployed]=useState(false); const [message,setMessage]=useState('');
 const [projectName,setProjectName]=useState('my-app'); const [repo,setRepo]=useState(''); const [ref,setRef]=useState('main'); const [serviceType,setServiceType]=useState('web'); const [containerPort,setContainerPort]=useState('3000'); const [hostPort,setHostPort]=useState('8088'); const [domain,setDomain]=useState(''); const [healthPath,setHealthPath]=useState('/'); const [command,setCommand]=useState('');
 const [deployments,setDeployments]=useState<Deployment[]>([]);
 async function loadDeployments(){try{const r=await fetch(`${API}/api/v1/deployments`);if(r.ok)setDeployments(await r.json());}catch{}}
 useEffect(()=>{loadDeployments()},[]);
 async function deploy(){
  setBusy(true);setMessage('Creating project…');
  try{
   const p=await fetch(`${API}/api/v1/projects`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({name:projectName||'my-app',repo:repo||undefined})});
   const project=await p.json(); if(!p.ok)throw new Error(project.detail||project.error||'Project creation failed');
   if(domain.trim()){
    const dr=await fetch(`${API}/api/v1/domains`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({projectId:project.id,domain:domain.trim()})});
    const d=await dr.json(); if(!dr.ok)throw new Error(d.detail||d.error||'Domain registration failed');
    throw new Error(`Domain registered. Add TXT ${d.verification.name} = ${d.verification.value}, verify it with /api/v1/domains/${d.id}/verify, then deploy again.`);
   }
   setMessage(repo?'Building repository…':'Starting runtime…');
   const isPublic=serviceType==='web';
   const d=await fetch(`${API}/api/v1/deployments`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({projectId:project.id,repo:repo||undefined,ref:ref||'main',image:repo?undefined:'nginx:alpine',serviceType,public:isPublic,healthMode:serviceType==='worker'||serviceType==='cron'?'process':'auto',command:command.trim()?command.trim().split(/\s+/):undefined,hostPort:isPublic?Number(hostPort)||undefined:undefined,containerPort:Number(containerPort)||80,healthPath:isPublic?(healthPath||undefined):undefined})});
   const result=await d.json(); if(!d.ok)throw new Error(result.detail||result.error||'Deployment failed');
   setDeployed(true);setOpen(false);setMessage(result.runtime?.url?`Deployment accepted → ${result.runtime.url}`:'Deployment accepted; waiting for the worker');await loadDeployments();
  }catch(e){setMessage(e instanceof Error?e.message:'Deployment failed');}finally{setBusy(false)}
 }
 return <main>
  <aside><div className="brand"><div className="logo">N</div><div><b>NEXUS</b><small>HOSTING</small></div></div><nav><a className="active">Overview</a><a>Projects</a><a>Services</a><a>Deployments</a><a>Domains</a><a>Observability</a></nav><div className="sideCard"><Sparkles size={17}/><b>Autopilot</b><span>Runtime-aware infrastructure recommendations.</span></div></aside>
  <section className="content"><header><div><span className="eyebrow">CONTROL PLANE / PRODUCTION</span><h1>Deploy the application, not the infrastructure.</h1><p>Frontend, backend, APIs, workers and private services run through one deployment graph with health checks, routing and recovery.</p></div><button onClick={()=>setOpen(true)}><Rocket size={17}/>New deployment</button></header>
   {message&&<div className="toast"><ShieldCheck size={18}/><span><b>Deployment status</b><small>{message}</small></span></div>}
   {open&&<div className="modalBackdrop"><div className="deployModal"><div className="modalHead"><div><span className="eyebrow">NEW DEPLOYMENT</span><h2>Deploy any application</h2></div><button className="close" onClick={()=>setOpen(false)}><X size={17}/></button></div><label>Project name<input value={projectName} onChange={e=>setProjectName(e.target.value)} placeholder="my-app"/></label><label>Git repository URL <span>(or leave empty for an image)</span><input value={repo} onChange={e=>setRepo(e.target.value)} placeholder="https://github.com/owner/repository"/></label><div className="formGrid"><label>Service type<select value={serviceType} onChange={e=>setServiceType(e.target.value)}><option value="web">Web / frontend / API</option><option value="worker">Worker</option><option value="private">Private service</option><option value="cron">Cron / job</option></select></label><label>Branch / ref<input value={ref} onChange={e=>setRef(e.target.value)} placeholder="main"/></label></div><div className="formGrid"><label>Container port<input type="number" value={containerPort} onChange={e=>setContainerPort(e.target.value)} /></label><label>Host port<input type="number" value={hostPort} onChange={e=>setHostPort(e.target.value)} disabled={serviceType!=='web'} /></label></div><div className="formGrid"><label>Start command <span>(optional)</span><input value={command} onChange={e=>setCommand(e.target.value)} placeholder="npm start / python app.py" /></label><label>Health path <span>(web only)</span><input value={healthPath} onChange={e=>setHealthPath(e.target.value)} placeholder="/health" disabled={serviceType!=='web'} /></label></div><label>Custom domain <span>(web only; verify DNS first)</span><input value={domain} onChange={e=>setDomain(e.target.value)} placeholder="app.example.com" disabled={serviceType!=='web'} /></label><div className="modalNote">Dockerfiles are preferred. Without one, Nexus auto-detects common Node.js, Python, Go, Java, Rust, .NET, PHP and Ruby projects and builds a production image.</div><button className="deployAction" onClick={deploy} disabled={busy}><Rocket size={16}/>{busy?'Deploying…':'Deploy now'}</button></div></div>}
   <div className="heroGrid"><div className="heroCard"><div className="status"><i/>{deployed?'Runtime deployed':'Control plane ready'}</div><div className="metric"><strong>{deployments.length||0}</strong><span>deployments tracked</span></div><div className="graph"><div className="node source"><GitBranch/><b>Source</b><small>{repo||'container image'}</small></div><div className="line"/><div className="node"><Globe2/><b>{serviceType==='worker'?'Worker':'Runtime'}</b><small>{deployed?'running':'ready'}</small></div><div className="line"/><div className="node"><Database/><b>Data</b><small>connectable</small></div></div></div><div className="insight"><div className="icon"><Sparkles/></div><span className="eyebrow">NEXUS AUTOPILOT</span><h2>One graph. Every workload.</h2><p>Use web services, workers and private services together instead of forcing every workload into a web server.</p><button className="ghost">Explore environments <ArrowUpRight size={15}/></button></div></div>
   <div className="sectionHead"><div><span className="eyebrow">SERVICES</span><h2>Built for real workloads</h2></div><button className="ghost">View catalog <ArrowUpRight size={15}/></button></div>
   <div className="services">{services.map(([name,desc,icon])=>{const I=icon==='Database'?Database:icon==='Globe2'?Globe2:icon==='Boxes'?Boxes:ShieldCheck;return <div className="service" key={name}><div className="serviceTop"><div className="icon"><I/></div><span className="live">AVAILABLE</span></div><h3>{name}</h3><p>{desc}</p><div className="serviceFoot"><span><Activity size={13}/> runtime ready</span><ArrowUpRight size={15}/></div></div>})}</div>
   <div className="terminal"><div className="termHead"><span><Terminal size={14}/> live deployment stream</span><span>production / runtime</span></div>{deployments.length?deployments.slice(0,4).map(d=><div key={d.id}><em>{new Date(d.createdAt).toLocaleTimeString()}</em> <b>{d.status.toUpperCase()}</b> {d.repo||'container deployment'}{d.runtime?.url?` → ${d.runtime.url}`:''}</div>):<div><em>READY</em> <b>PLAN</b> Runtime catalog loaded</div>}</div>
  </section>
 </main>;
}
