import Docker from 'dockerode';
import http from 'node:http';
import { buildFromGit } from './build.js';
import { deployRuntime, rollbackRuntime } from './deploy.js';
import { DeploymentQueue } from './queue.js';

const docker = process.platform === 'win32' ? new Docker({ socketPath: '\\\\.\\pipe\\docker_engine' }) : new Docker({ socketPath: process.env.DOCKER_SOCKET ?? '/var/run/docker.sock' });
const port = Number(process.env.PORT ?? 4100);
const queue = new DeploymentQueue();
type DeployBody={name:string;image:string;containerPort?:number;hostPort?:number;env?:Record<string,string>};
function readBody(req:http.IncomingMessage):Promise<string>{return new Promise((resolve,reject)=>{let b='';req.on('data',c=>b+=c);req.on('end',()=>resolve(b));req.on('error',reject);});}
async function main(req:http.IncomingMessage,res:http.ServerResponse){res.setHeader('content-type','application/json');try{if(req.url==='/health'){res.end(JSON.stringify({ok:true,docker:!!(await docker.ping()),queue:queue.stats()}));return;}if(req.url==='/api/v1/queue'){res.end(JSON.stringify(queue.stats()));return;}if(req.url==='/api/v1/runtime/containers'){res.end(JSON.stringify(await docker.listContainers({all:true})));return;}if(req.url==='/api/v1/runtime/deploy'&&req.method==='POST'){const b=JSON.parse(await readBody(req)) as DeployBody;if(!b.name||!b.image){res.statusCode=400;res.end(JSON.stringify({error:'name and image are required'}));return;}res.statusCode=202;res.end(JSON.stringify({accepted:true,queued:true,name:b.name}));queue.enqueue(async()=>{try{await deployRuntime(b);}catch(e){console.error('runtime deployment failed',e);}});return;}if(req.url==='/api/v1/runtime/rollback'&&req.method==='POST'){const b=JSON.parse(await readBody(req)) as DeployBody & {previousImage:string};if(!b.name||!b.previousImage){res.statusCode=400;res.end(JSON.stringify({error:'name and previousImage are required'}));return;}res.statusCode=202;res.end(JSON.stringify({accepted:true,queued:true,name:b.name}));queue.enqueue(async()=>{try{await rollbackRuntime(b);}catch(e){console.error('rollback failed',e);}});return;}if(req.url==='/api/v1/runtime/build'&&req.method==='POST'){const b=JSON.parse(await readBody(req));if(!b.repo||!b.image){res.statusCode=400;res.end(JSON.stringify({error:'repo and image are required'}));return;}res.end(JSON.stringify(await buildFromGit(b)));return;}if(req.url?.startsWith('/api/v1/runtime/logs/')){const name=decodeURIComponent(req.url.split('/').pop()!);const logs=await docker.getContainer(name).logs({stdout:true,stderr:true,tail:200});res.end(JSON.stringify({name,logs:logs.toString()}));return;}res.statusCode=404;res.end(JSON.stringify({error:'Not found'}));}catch(e){res.statusCode=500;res.end(JSON.stringify({error:String(e)}));}}
http.createServer(main).listen(port,'0.0.0.0',()=>console.log(`Nexus engine listening on ${port}`));
