import pg from 'pg';
const { Pool } = pg;

/** Provider-neutral GA data primitives for billing, backups, webhooks, SLOs and support. */
export async function ensureMarketSchema() {
  const pool = new Pool({ connectionString: process.env.DATABASE_URL ?? 'postgres://nexus:nexus_dev_only@127.0.0.1:5432/nexus' });
  try {
    await pool.query(`
      CREATE TABLE IF NOT EXISTS subscriptions (id uuid PRIMARY KEY, organization_id uuid NOT NULL REFERENCES organizations(id) ON DELETE CASCADE, plan text NOT NULL, status text NOT NULL DEFAULT 'trialing', external_customer_ref text, external_subscription_ref text, current_period_start timestamptz, current_period_end timestamptz, cancel_at_period_end boolean NOT NULL DEFAULT false, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), UNIQUE(organization_id));
      CREATE TABLE IF NOT EXISTS invoices (id uuid PRIMARY KEY, organization_id uuid NOT NULL REFERENCES organizations(id) ON DELETE CASCADE, subscription_id uuid REFERENCES subscriptions(id) ON DELETE SET NULL, external_invoice_ref text, status text NOT NULL DEFAULT 'draft', currency text NOT NULL DEFAULT 'USD', amount_minor bigint NOT NULL DEFAULT 0, period_start timestamptz, period_end timestamptz, hosted_invoice_url text, created_at timestamptz NOT NULL DEFAULT now());
      CREATE TABLE IF NOT EXISTS backup_jobs (id uuid PRIMARY KEY, organization_id uuid REFERENCES organizations(id) ON DELETE CASCADE, project_id uuid REFERENCES projects(id) ON DELETE CASCADE, service_id uuid REFERENCES services(id) ON DELETE CASCADE, kind text NOT NULL, status text NOT NULL DEFAULT 'queued', storage_key text, checksum text, size_bytes bigint, started_at timestamptz, completed_at timestamptz, expires_at timestamptz, error text, created_at timestamptz NOT NULL DEFAULT now());
      CREATE INDEX IF NOT EXISTS backup_jobs_project_idx ON backup_jobs(project_id,created_at DESC);
      CREATE TABLE IF NOT EXISTS restore_jobs (id uuid PRIMARY KEY, backup_id uuid NOT NULL REFERENCES backup_jobs(id) ON DELETE RESTRICT, project_id uuid NOT NULL REFERENCES projects(id) ON DELETE CASCADE, status text NOT NULL DEFAULT 'queued', target_service_id uuid REFERENCES services(id) ON DELETE SET NULL, started_at timestamptz, completed_at timestamptz, error text, created_at timestamptz NOT NULL DEFAULT now());
      CREATE TABLE IF NOT EXISTS webhook_endpoints (id uuid PRIMARY KEY, organization_id uuid NOT NULL REFERENCES organizations(id) ON DELETE CASCADE, url text NOT NULL, secret_hash text NOT NULL, events jsonb NOT NULL DEFAULT '[]', active boolean NOT NULL DEFAULT true, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
      CREATE TABLE IF NOT EXISTS webhook_deliveries (id uuid PRIMARY KEY, endpoint_id uuid NOT NULL REFERENCES webhook_endpoints(id) ON DELETE CASCADE, event_id text NOT NULL, event_type text NOT NULL, status text NOT NULL DEFAULT 'queued', attempts integer NOT NULL DEFAULT 0, response_code integer, next_attempt_at timestamptz, delivered_at timestamptz, last_error text, created_at timestamptz NOT NULL DEFAULT now(), UNIQUE(endpoint_id,event_id));
      CREATE TABLE IF NOT EXISTS notification_preferences (organization_id uuid PRIMARY KEY REFERENCES organizations(id) ON DELETE CASCADE, email boolean NOT NULL DEFAULT true, webhook boolean NOT NULL DEFAULT true, chatops boolean NOT NULL DEFAULT false, incident_alerts boolean NOT NULL DEFAULT true, deployment_alerts boolean NOT NULL DEFAULT true, updated_at timestamptz NOT NULL DEFAULT now());
      CREATE TABLE IF NOT EXISTS artifact_registry (id uuid PRIMARY KEY, organization_id uuid REFERENCES organizations(id) ON DELETE CASCADE, project_id uuid REFERENCES projects(id) ON DELETE CASCADE, repository text NOT NULL, tag text, digest text NOT NULL, immutable boolean NOT NULL DEFAULT true, size_bytes bigint, metadata jsonb NOT NULL DEFAULT '{}', created_at timestamptz NOT NULL DEFAULT now(), UNIQUE(repository,digest));
      CREATE TABLE IF NOT EXISTS slo_policies (id uuid PRIMARY KEY, project_id uuid NOT NULL REFERENCES projects(id) ON DELETE CASCADE, availability_target numeric NOT NULL DEFAULT 99.9, latency_p95_ms integer, error_rate_target numeric, window_days integer NOT NULL DEFAULT 30, enabled boolean NOT NULL DEFAULT true, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), UNIQUE(project_id));
      CREATE TABLE IF NOT EXISTS slo_measurements (id uuid PRIMARY KEY, slo_id uuid NOT NULL REFERENCES slo_policies(id) ON DELETE CASCADE, availability numeric, latency_p95_ms numeric, error_rate numeric, window_start timestamptz NOT NULL, window_end timestamptz NOT NULL, budget_remaining numeric, created_at timestamptz NOT NULL DEFAULT now());
      CREATE TABLE IF NOT EXISTS abuse_events (id uuid PRIMARY KEY, organization_id uuid REFERENCES organizations(id) ON DELETE CASCADE, project_id uuid REFERENCES projects(id) ON DELETE CASCADE, category text NOT NULL, severity text NOT NULL DEFAULT 'warning', source text, details jsonb NOT NULL DEFAULT '{}', resolved_at timestamptz, created_at timestamptz NOT NULL DEFAULT now());
      CREATE TABLE IF NOT EXISTS disaster_recovery_drills (id uuid PRIMARY KEY, organization_id uuid REFERENCES organizations(id) ON DELETE CASCADE, scenario text NOT NULL, status text NOT NULL DEFAULT 'planned', rto_seconds integer, rpo_seconds integer, evidence jsonb NOT NULL DEFAULT '{}', started_at timestamptz, completed_at timestamptz, created_at timestamptz NOT NULL DEFAULT now());
      CREATE TABLE IF NOT EXISTS support_tickets (id uuid PRIMARY KEY, organization_id uuid REFERENCES organizations(id) ON DELETE SET NULL, user_id uuid REFERENCES users(id) ON DELETE SET NULL, subject text NOT NULL, status text NOT NULL DEFAULT 'open', priority text NOT NULL DEFAULT 'normal', body text NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
    `);
  } finally { await pool.end(); }
}
