import pg from 'pg';
const { Pool } = pg;
export async function ensurePlatformSchema() {
  const pool = new Pool({ connectionString: process.env.DATABASE_URL ?? 'postgres://nexus:nexus_dev_only@127.0.0.1:5432/nexus' });
  try { await pool.query(`
CREATE TABLE IF NOT EXISTS organizations (id uuid PRIMARY KEY,name text NOT NULL,slug text NOT NULL UNIQUE,created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS organization_members (organization_id uuid NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,role text NOT NULL CHECK(role IN ('owner','admin','developer','viewer')),created_at timestamptz NOT NULL DEFAULT now(),PRIMARY KEY(organization_id,user_id));
ALTER TABLE projects ADD COLUMN IF NOT EXISTS organization_id uuid REFERENCES organizations(id) ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS projects_organization_idx ON projects(organization_id,created_at DESC);
CREATE TABLE IF NOT EXISTS environments (id uuid PRIMARY KEY,project_id uuid NOT NULL REFERENCES projects(id) ON DELETE CASCADE,name text NOT NULL,slug text NOT NULL,created_at timestamptz NOT NULL DEFAULT now(),UNIQUE(project_id,slug));
CREATE TABLE IF NOT EXISTS services (id uuid PRIMARY KEY,environment_id uuid NOT NULL REFERENCES environments(id) ON DELETE CASCADE,name text NOT NULL,type text NOT NULL CHECK(type IN ('web','worker','cron','private','database','redis')),source jsonb NOT NULL DEFAULT '{}',config jsonb NOT NULL DEFAULT '{}',created_at timestamptz NOT NULL DEFAULT now(),UNIQUE(environment_id,name));
CREATE TABLE IF NOT EXISTS secrets (id uuid PRIMARY KEY,environment_id uuid NOT NULL REFERENCES environments(id) ON DELETE CASCADE,service_id uuid REFERENCES services(id) ON DELETE CASCADE,name text NOT NULL,encrypted_value text NOT NULL,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now());
CREATE UNIQUE INDEX IF NOT EXISTS secrets_environment_name_global_idx ON secrets(environment_id,name) WHERE service_id IS NULL;
CREATE UNIQUE INDEX IF NOT EXISTS secrets_environment_service_name_idx ON secrets(environment_id,service_id,name) WHERE service_id IS NOT NULL;
CREATE TABLE IF NOT EXISTS api_tokens (id uuid PRIMARY KEY,user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,name text NOT NULL,token_hash text NOT NULL UNIQUE,scopes jsonb NOT NULL DEFAULT '[]',expires_at timestamptz,last_used_at timestamptz,created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS audit_logs (id uuid PRIMARY KEY,organization_id uuid REFERENCES organizations(id) ON DELETE CASCADE,user_id uuid REFERENCES users(id) ON DELETE SET NULL,action text NOT NULL,resource_type text NOT NULL,resource_id text,metadata jsonb NOT NULL DEFAULT '{}',created_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX IF NOT EXISTS audit_logs_org_created_idx ON audit_logs(organization_id,created_at DESC);
CREATE TABLE IF NOT EXISTS usage_events (id uuid PRIMARY KEY,organization_id uuid REFERENCES organizations(id) ON DELETE CASCADE,project_id uuid REFERENCES projects(id) ON DELETE CASCADE,service_id uuid REFERENCES services(id) ON DELETE CASCADE,metric text NOT NULL,quantity numeric NOT NULL CHECK(quantity>=0),unit text NOT NULL,recorded_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX IF NOT EXISTS usage_events_org_recorded_idx ON usage_events(organization_id,recorded_at DESC);
CREATE TABLE IF NOT EXISTS volumes (id uuid PRIMARY KEY,service_id uuid NOT NULL REFERENCES services(id) ON DELETE CASCADE,name text NOT NULL,size_bytes bigint NOT NULL CHECK(size_bytes>0),mount_path text NOT NULL,provider text NOT NULL DEFAULT 'docker',created_at timestamptz NOT NULL DEFAULT now(),UNIQUE(service_id,name));
CREATE TABLE IF NOT EXISTS database_instances (id uuid PRIMARY KEY,service_id uuid NOT NULL REFERENCES services(id) ON DELETE CASCADE,engine text NOT NULL CHECK(engine IN ('postgres','redis')),version text,status text NOT NULL DEFAULT 'provisioning',created_at timestamptz NOT NULL DEFAULT now());
ALTER TABLE database_instances ADD COLUMN IF NOT EXISTS connection_uri_secret_id uuid REFERENCES secrets(id) ON DELETE SET NULL;
ALTER TABLE database_instances ADD COLUMN IF NOT EXISTS endpoint text; ALTER TABLE database_instances ADD COLUMN IF NOT EXISTS container_name text; ALTER TABLE database_instances ADD COLUMN IF NOT EXISTS updated_at timestamptz NOT NULL DEFAULT now();
CREATE TABLE IF NOT EXISTS runtime_nodes (id uuid PRIMARY KEY,name text NOT NULL UNIQUE,endpoint text NOT NULL,region text NOT NULL DEFAULT 'local',capacity_cpu_millis integer NOT NULL DEFAULT 1000 CHECK(capacity_cpu_millis>0),capacity_memory_bytes bigint NOT NULL DEFAULT 1073741824 CHECK(capacity_memory_bytes>0),used_cpu_millis integer NOT NULL DEFAULT 0 CHECK(used_cpu_millis>=0),used_memory_bytes bigint NOT NULL DEFAULT 0 CHECK(used_memory_bytes>=0),status text NOT NULL DEFAULT 'online' CHECK(status IN ('online','draining','offline')),last_heartbeat_at timestamptz NOT NULL DEFAULT now(),created_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX IF NOT EXISTS runtime_nodes_heartbeat_idx ON runtime_nodes(status,last_heartbeat_at DESC);
CREATE TABLE IF NOT EXISTS cron_jobs (id uuid PRIMARY KEY,service_id uuid NOT NULL REFERENCES services(id) ON DELETE CASCADE,schedule text NOT NULL,command jsonb NOT NULL DEFAULT '[]',timezone text NOT NULL DEFAULT 'UTC',enabled boolean NOT NULL DEFAULT true,last_run_at timestamptz,next_run_at timestamptz,created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS deployment_events (id uuid PRIMARY KEY,deployment_id uuid NOT NULL REFERENCES deployments(id) ON DELETE CASCADE,phase text NOT NULL,message text NOT NULL,metadata jsonb NOT NULL DEFAULT '{}',created_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX IF NOT EXISTS deployment_events_deployment_idx ON deployment_events(deployment_id,created_at ASC);
CREATE TABLE IF NOT EXISTS recovery_points (id uuid PRIMARY KEY,project_id uuid NOT NULL REFERENCES projects(id) ON DELETE CASCADE,deployment_id uuid REFERENCES deployments(id) ON DELETE SET NULL,service_id uuid,label text NOT NULL,image text,runtime jsonb NOT NULL DEFAULT '{}',created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS application_graph_nodes (id uuid PRIMARY KEY,project_id uuid NOT NULL REFERENCES projects(id) ON DELETE CASCADE,service_id uuid,node_key text NOT NULL,name text NOT NULL,type text NOT NULL,status text NOT NULL DEFAULT 'unknown',metadata jsonb NOT NULL DEFAULT '{}',created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now(),UNIQUE(project_id,node_key));
CREATE TABLE IF NOT EXISTS application_graph_edges (id uuid PRIMARY KEY,project_id uuid NOT NULL REFERENCES projects(id) ON DELETE CASCADE,source_node_id uuid NOT NULL REFERENCES application_graph_nodes(id) ON DELETE CASCADE,target_node_id uuid NOT NULL REFERENCES application_graph_nodes(id) ON DELETE CASCADE,type text NOT NULL DEFAULT 'depends_on',metadata jsonb NOT NULL DEFAULT '{}',created_at timestamptz NOT NULL DEFAULT now(),UNIQUE(source_node_id,target_node_id,type));
CREATE TABLE IF NOT EXISTS autoscaling_policies (id uuid PRIMARY KEY,service_id uuid NOT NULL REFERENCES services(id) ON DELETE CASCADE,min_replicas integer NOT NULL CHECK(min_replicas>0),max_replicas integer NOT NULL CHECK(max_replicas>=min_replicas),cpu_percent numeric,memory_percent numeric,requests_per_second numeric,queue_depth numeric,cooldown_seconds integer NOT NULL DEFAULT 60 CHECK(cooldown_seconds>=0),enabled boolean NOT NULL DEFAULT true,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now(),UNIQUE(service_id));
CREATE TABLE IF NOT EXISTS autoscaling_decisions (id uuid PRIMARY KEY,service_id uuid NOT NULL REFERENCES services(id) ON DELETE CASCADE,current_replicas integer NOT NULL,desired_replicas integer NOT NULL,reason text NOT NULL,metrics jsonb NOT NULL DEFAULT '{}',created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS incidents (id uuid PRIMARY KEY,project_id uuid REFERENCES projects(id) ON DELETE CASCADE,deployment_id uuid REFERENCES deployments(id) ON DELETE SET NULL,severity text NOT NULL DEFAULT 'warning',status text NOT NULL DEFAULT 'open',title text NOT NULL,details jsonb NOT NULL DEFAULT '{}',created_at timestamptz NOT NULL DEFAULT now(),resolved_at timestamptz);
CREATE TABLE IF NOT EXISTS release_policies (project_id uuid PRIMARY KEY REFERENCES projects(id) ON DELETE CASCADE,strategy text NOT NULL DEFAULT 'rolling' CHECK(strategy IN('rolling','blue_green','canary')),canary_steps jsonb NOT NULL DEFAULT '[5,25,50,100]',zero_downtime boolean NOT NULL DEFAULT true,rollback_on_failure boolean NOT NULL DEFAULT true,updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS release_gates (id uuid PRIMARY KEY,project_id uuid NOT NULL REFERENCES projects(id) ON DELETE CASCADE,name text NOT NULL,kind text NOT NULL,required boolean NOT NULL DEFAULT true,config jsonb NOT NULL DEFAULT '{}',created_at timestamptz NOT NULL DEFAULT now(),UNIQUE(project_id,name));
CREATE TABLE IF NOT EXISTS release_gate_runs (id uuid PRIMARY KEY,gate_id uuid NOT NULL REFERENCES release_gates(id) ON DELETE CASCADE,deployment_id uuid NOT NULL REFERENCES deployments(id) ON DELETE CASCADE,status text NOT NULL,details jsonb NOT NULL DEFAULT '{}',started_at timestamptz,finished_at timestamptz,created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS preview_policies (project_id uuid PRIMARY KEY REFERENCES projects(id) ON DELETE CASCADE,access text NOT NULL DEFAULT 'team',require_auth boolean NOT NULL DEFAULT true,expires_hours integer NOT NULL DEFAULT 168,updated_at timestamptz NOT NULL DEFAULT now());
ALTER TABLE preview_policies ADD COLUMN IF NOT EXISTS mode text;
UPDATE preview_policies SET mode=COALESCE(mode,access,'team') WHERE mode IS NULL;
ALTER TABLE preview_policies ALTER COLUMN mode SET DEFAULT 'team';
CREATE TABLE IF NOT EXISTS deployment_comments (id uuid PRIMARY KEY,deployment_id uuid NOT NULL REFERENCES deployments(id) ON DELETE CASCADE,user_id uuid REFERENCES users(id) ON DELETE SET NULL,body text NOT NULL CHECK(length(body) BETWEEN 1 AND 4000),created_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX IF NOT EXISTS deployment_comments_deployment_idx ON deployment_comments(deployment_id,created_at ASC);
CREATE TABLE IF NOT EXISTS project_settings (project_id uuid PRIMARY KEY REFERENCES projects(id) ON DELETE CASCADE,settings jsonb NOT NULL DEFAULT '{}',updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS deployment_artifacts (id uuid PRIMARY KEY,deployment_id uuid NOT NULL REFERENCES deployments(id) ON DELETE CASCADE,organization_id uuid REFERENCES organizations(id) ON DELETE CASCADE,repository text,ref text,source_commit text,image text NOT NULL,image_id text NOT NULL,digest text,created_at timestamptz NOT NULL DEFAULT now(),UNIQUE(deployment_id),UNIQUE(image_id));
CREATE INDEX IF NOT EXISTS deployment_artifacts_org_created_idx ON deployment_artifacts(organization_id,created_at DESC);
CREATE INDEX IF NOT EXISTS deployment_artifacts_source_commit_idx ON deployment_artifacts(repository,source_commit);
CREATE OR REPLACE FUNCTION capture_deployment_artifact() RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE artifact jsonb; org_id uuid;
BEGIN
  artifact := COALESCE(NEW.runtime->'buildProvenance', NEW.runtime->'artifactProvenance', '{}'::jsonb);
  IF artifact ? 'imageId' AND NULLIF(artifact->>'imageId','') IS NOT NULL THEN
    SELECT p.organization_id INTO org_id FROM projects p WHERE p.id=NEW.project_id;
    INSERT INTO deployment_artifacts(id,deployment_id,organization_id,repository,ref,source_commit,image,image_id,digest,created_at)
    VALUES(gen_random_uuid(),NEW.id,org_id,NULLIF(artifact->>'repository',''),NULLIF(artifact->>'ref',''),NULLIF(artifact->>'sourceCommit',''),COALESCE(NULLIF(artifact->>'image',''),NEW.image),artifact->>'imageId',NULLIF(artifact->>'digest',''),COALESCE(NULLIF(artifact->>'createdAt','')::timestamptz,NOW()))
    ON CONFLICT(deployment_id) DO UPDATE SET organization_id=EXCLUDED.organization_id,repository=EXCLUDED.repository,ref=EXCLUDED.ref,source_commit=EXCLUDED.source_commit,image=EXCLUDED.image,image_id=EXCLUDED.image_id,digest=EXCLUDED.digest,created_at=EXCLUDED.created_at;
  END IF;
  RETURN NEW;
END $$;
DROP TRIGGER IF EXISTS deployments_capture_artifact ON deployments;
CREATE TRIGGER deployments_capture_artifact AFTER INSERT OR UPDATE OF runtime ON deployments FOR EACH ROW EXECUTE FUNCTION capture_deployment_artifact();
`); } finally { await pool.end(); }
}
