import type { FastifyInstance } from 'fastify';
import { createHash, createCipheriv, randomBytes, randomUUID } from 'node:crypto';
import pg from 'pg';
import { userFromToken } from './auth.js';
const { Pool } = pg;
const pool = new Pool({ connectionString: process.env.DATABASE_URL ?? 'postgres://nexus:nexus_dev_only@127.0.0.1:5432/nexus' });
const cookieToken=(req:any)=>{const raw=String(req.headers.cookie??'');for(const part of raw.split(';')){const [k,...v]=part.trim().split('=');if(k==='nexus_session')return decodeURIComponent(v.join('='));}return undefined;};
const requireUser=async(req:any,reply:any)=>{const user=await userFromToken(cookieToken(req));if(!user){reply.code(401).send({error:'Authentication required'});return undefined;}return user;};
const secretKey=()=>createHash('sha256').update(process.env.SECRETS_ENCRYPTION_KEY??process.env.AUTH_SECRET??'change-this-secret-in-production').digest();
const encryptSecret=(value:string)=>{const iv=randomBytes(12);const cipher=createCipheriv('aes-256-gcm',secretKey(),iv);const body=Buffer.concat([cipher.update(value,'utf8'),cipher.final()]);return `${iv.toString('base64url')}.${cipher.getAuthTag().toString('base64url')}.${body.toString('base64url')}`;};
const slug=(value:string)=>value.toLowerCase().trim().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'').slice(0,50)||'project';

export async function registerPlatformRoutes(app:FastifyInstance){
  app.get('/api/v1/platform/overview',async(req,reply)=>{const user=await requireUser(req,reply);if(!user)return;const [{rows:orgs},{rows:projects},{rows:services},{rows:deployments}]=await Promise.all([pool.query('SELECT o.id,o.name,o.slug,om.role FROM organizations o JOIN organization_members om ON om.organization_id=o.id WHERE om.user_id=$1 ORDER BY o.created_at DESC',[user.id]),pool.query('SELECT p.id,p.name,p.repo,p.organization_id AS "organizationId",p.created_at AS "createdAt" FROM projects p JOIN organization_members om ON om.organization_id=p.organization_id WHERE om.user_id=$1 ORDER BY p.created_at DESC',[user.id]),pool.query('SELECT s.id,s.name,s.type,e.name AS environment,p.name AS project FROM services s JOIN environments e ON e.id=s.environment_id JOIN projects p ON p.id=e.project_id JOIN organization_members om ON om.organization_id=p.organization_id WHERE om.user_id=$1 ORDER BY s.created_at DESC',[user.id]),pool.query('SELECT d.id,d.status,d.created_at AS "createdAt",p.name AS project FROM deployments d JOIN projects p ON p.id=d.project_id JOIN organization_members om ON om.organization_id=p.organization_id WHERE om.user_id=$1 ORDER BY d.created_at DESC LIMIT 50',[user.id])]);return {organizations:orgs,projects,services,deployments};});

  app.post('/api/v1/organizations',async(req,reply)=>{const user=await requireUser(req,reply);if(!user)return;const body=req.body as {name?:string};if(!body.name?.trim())return reply.code(400).send({error:'name is required'});const id=randomUUID();const base=slug(body.name);const unique=`${base}-${id.slice(0,6)}`;await pool.query('BEGIN');try{await pool.query('INSERT INTO organizations(id,name,slug) VALUES($1,$2,$3)',[id,body.name.trim(),unique]);await pool.query('INSERT INTO organization_members(organization_id,user_id,role) VALUES($1,$2,$3)',[id,user.id,'owner']);await pool.query('COMMIT');return reply.code(201).send({id,name:body.name.trim(),slug:unique,role:'owner'});}catch(error){await pool.query('ROLLBACK');throw error;}});

  app.post('/api/v1/projects/:projectId/environments',async(req,reply)=>{const user=await requireUser(req,reply);if(!user)return;const projectId=String((req.params as any).projectId);const body=req.body as {name?:string};if(!body.name?.trim())return reply.code(400).send({error:'name is required'});const access=await pool.query('SELECT 1 FROM projects p JOIN organization_members om ON om.organization_id=p.organization_id WHERE p.id=$1 AND om.user_id=$2',[projectId,user.id]);if(!access.rowCount)return reply.code(404).send({error:'Project not found'});const id=randomUUID();const environmentSlug=slug(body.name);await pool.query('INSERT INTO environments(id,project_id,name,slug) VALUES($1,$2,$3,$4)',[id,projectId,body.name.trim(),environmentSlug]);return reply.code(201).send({id,projectId,name:body.name.trim(),slug:environmentSlug});});

  app.get('/api/v1/environments/:environmentId/services',async(req,reply)=>{const user=await requireUser(req,reply);if(!user)return;const id=String((req.params as any).environmentId);const {rows}=await pool.query('SELECT s.id,s.name,s.type,s.source,s.config,s.created_at AS "createdAt" FROM services s JOIN environments e ON e.id=s.environment_id JOIN projects p ON p.id=e.project_id JOIN organization_members om ON om.organization_id=p.organization_id WHERE s.environment_id=$1 AND om.user_id=$2 ORDER BY s.created_at',[id,user.id]);return {services:rows};});

  app.post('/api/v1/environments/:environmentId/services',async(req,reply)=>{const user=await requireUser(req,reply);if(!user)return;const environmentId=String((req.params as any).environmentId);const body=req.body as {name?:string;type?:string;source?:unknown;config?:unknown};if(!body.name?.trim()||!['web','worker','cron','private','database','redis'].includes(body.type??''))return reply.code(400).send({error:'name and valid service type are required'});const access=await pool.query('SELECT 1 FROM environments e JOIN projects p ON p.id=e.project_id JOIN organization_members om ON om.organization_id=p.organization_id WHERE e.id=$1 AND om.user_id=$2',[environmentId,user.id]);if(!access.rowCount)return reply.code(404).send({error:'Environment not found'});const id=randomUUID();await pool.query('INSERT INTO services(id,environment_id,name,type,source,config) VALUES($1,$2,$3,$4,$5,$6)',[id,environmentId,body.name.trim(),body.type,JSON.stringify(body.source??{}),JSON.stringify(body.config??{})]);return reply.code(201).send({id,environmentId,name:body.name.trim(),type:body.type,source:body.source??{},config:body.config??{}});});

  app.put('/api/v1/environments/:environmentId/secrets/:name',async(req,reply)=>{const user=await requireUser(req,reply);if(!user)return;const environmentId=String((req.params as any).environmentId);const name=String((req.params as any).name);const body=req.body as {value?:string;serviceId?:string|null};if(typeof body.value!=='string')return reply.code(400).send({error:'value is required'});const access=await pool.query('SELECT 1 FROM environments e JOIN projects p ON p.id=e.project_id JOIN organization_members om ON om.organization_id=p.organization_id WHERE e.id=$1 AND om.user_id=$2',[environmentId,user.id]);if(!access.rowCount)return reply.code(404).send({error:'Environment not found'});const id=randomUUID();await pool.query(`INSERT INTO secrets(id,environment_id,service_id,name,encrypted_value) VALUES($1,$2,$3,$4,$5) ON CONFLICT(environment_id,service_id,name) DO UPDATE SET encrypted_value=EXCLUDED.encrypted_value,updated_at=NOW()`,[id,environmentId,body.serviceId??null,name,encryptSecret(body.value)]);await pool.query('INSERT INTO audit_logs(id,user_id,action,resource_type,resource_id,metadata) VALUES($1,$2,$3,$4,$5,$6)',[randomUUID(),user.id,'secret.updated','secret',name,JSON.stringify({environmentId,serviceId:body.serviceId??null})]);return {ok:true,name,updated:true};});

  app.post('/api/v1/usage',async(req,reply)=>{const user=await requireUser(req,reply);if(!user)return;const body=req.body as {organizationId?:string;projectId?:string;serviceId?:string;metric?:string;quantity?:number;unit?:string};if(!body.organizationId||!body.metric||typeof body.quantity!=='number'||!body.unit)return reply.code(400).send({error:'organizationId, metric, quantity and unit are required'});const access=await pool.query('SELECT 1 FROM organization_members WHERE organization_id=$1 AND user_id=$2',[body.organizationId,user.id]);if(!access.rowCount)return reply.code(403).send({error:'Not a member of this organization'});await pool.query('INSERT INTO usage_events(id,organization_id,project_id,service_id,metric,quantity,unit) VALUES($1,$2,$3,$4,$5,$6,$7)',[randomUUID(),body.organizationId,body.projectId??null,body.serviceId??null,body.metric,body.quantity,body.unit]);return reply.code(202).send({accepted:true});});

  app.get('/api/v1/audit',async(req,reply)=>{const user=await requireUser(req,reply);if(!user)return;const q=req.query as {organizationId?:string;limit?:string};const limit=Math.min(200,Math.max(1,Number(q.limit??50)));const {rows}=await pool.query(`SELECT a.id,a.action,a.resource_type AS "resourceType",a.resource_id AS "resourceId",a.metadata,a.created_at AS "createdAt",u.email FROM audit_logs a LEFT JOIN users u ON u.id=a.user_id JOIN organization_members om ON om.organization_id=a.organization_id WHERE om.user_id=$1 ${q.organizationId?'AND a.organization_id=$2':''} ORDER BY a.created_at DESC LIMIT ${limit}`,q.organizationId?[user.id,q.organizationId]:[user.id]);return {audit:rows};});
}
