import type { FastifyInstance } from 'fastify';
import { randomUUID } from 'node:crypto';
import pg from 'pg';
import { requireUser } from './platform-routes.js';
const { Pool } = pg;
const pool = new Pool({ connectionString: process.env.DATABASE_URL ?? 'postgres://nexus:nexus_dev_only@127.0.0.1:5432/nexus' });

async function projectAccess(projectId:string,userId:string){const r=await pool.query('SELECT p.id,p.organization_id AS "organizationId" FROM projects p JOIN organization_members om ON om.organization_id=p.organization_id WHERE p.id=$1 AND om.user_id=$2 LIMIT 1',[projectId,userId]);return r.rows[0];}
async function ensureSchema(){await pool.query(`
CREATE TABLE IF NOT EXISTS release_gate_configs(id uuid PRIMARY KEY,project_id uuid NOT NULL REFERENCES projects(id) ON DELETE CASCADE,name text NOT NULL,kind text NOT NULL,required boolean NOT NULL DEFAULT true,config jsonb NOT NULL DEFAULT '{}'::jsonb,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now(),UNIQUE(project_id,name));
CREATE TABLE IF NOT EXISTS release_gate_results(id uuid PRIMARY KEY,deployment_id uuid NOT NULL REFERENCES deployments(id) ON DELETE CASCADE,gate_id uuid REFERENCES release_gate_configs(id) ON DELETE SET NULL,name text NOT NULL,status text NOT NULL CHECK(status IN ('pending','running','passed','failed','skipped')),message text,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now(),UNIQUE(deployment_id,name));
CREATE TABLE IF NOT EXISTS preview_policies(project_id uuid PRIMARY KEY REFERENCES projects(id) ON DELETE CASCADE,mode text NOT NULL DEFAULT 'team' CHECK(mode IN ('public','team','protected')),password_hash text,require_auth boolean NOT NULL DEFAULT false,expires_hours integer NOT NULL DEFAULT 72,updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS deployment_comments(id uuid PRIMARY KEY,deployment_id uuid NOT NULL REFERENCES deployments(id) ON DELETE CASCADE,user_id uuid REFERENCES users(id) ON DELETE SET NULL,body text NOT NULL,created_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX IF NOT EXISTS deployment_comments_idx ON deployment_comments(deployment_id,created_at ASC);
CREATE TABLE IF NOT EXISTS project_settings(project_id uuid PRIMARY KEY REFERENCES projects(id) ON DELETE CASCADE,settings jsonb NOT NULL DEFAULT '{}'::jsonb,updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS provider_catalog(id text PRIMARY KEY,name text NOT NULL,category text NOT NULL,description text NOT NULL,capabilities jsonb NOT NULL DEFAULT '[]'::jsonb,enabled boolean NOT NULL DEFAULT true,created_at timestamptz NOT NULL DEFAULT now());
INSERT INTO provider_catalog(id,name,category,description,capabilities) VALUES
('docker','Docker Runtime','runtime','Portable container execution on Nexus runtime nodes','["web","worker","cron","private"]'),
('postgres','PostgreSQL','database','Managed PostgreSQL through the Nexus database contract','["database","backup"]'),
('redis','Redis','database','Managed Redis through the Nexus database contract','["redis","cache"]'),
('github','GitHub','source','Git repository source and CI integration','["git","pull_requests","checks"]') ON CONFLICT(id) DO NOTHING;
`);}

export async function registerAdvancedPlatformRoutes(app:FastifyInstance){
 await ensureSchema();
 app.get('/api/v1/projects/:projectId/release-gates',async(req,reply)=>{const u=await requireUser(req,reply);if(!u)return;const id=String((req.params as any).projectId);if(!await projectAccess(id,u.id))return reply.code(404).send({error:'Project not found'});const {rows}=await pool.query('SELECT id,name,kind,required,config,created_at AS "createdAt",updated_at AS "updatedAt" FROM release_gate_configs WHERE project_id=$1 ORDER BY created_at',[id]);return {gates:rows};});
 app.put('/api/v1/projects/:projectId/release-gates',async(req,reply)=>{const u=await requireUser(req,reply);if(!u)return;const projectId=String((req.params as any).projectId);const access=await projectAccess(projectId,u.id);if(!access)return reply.code(404).send({error:'Project not found'});const body=req.body as {name?:string;kind?:string;required?:boolean;config?:unknown};if(!body.name?.trim()||!body.kind?.trim())return reply.code(400).send({error:'name and kind are required'});const id=randomUUID();const {rows}=await pool.query(`INSERT INTO release_gate_configs(id,project_id,name,kind,required,config) VALUES($1,$2,$3,$4,$5,$6) ON CONFLICT(project_id,name) DO UPDATE SET kind=EXCLUDED.kind,required=EXCLUDED.required,config=EXCLUDED.config,updated_at=NOW() RETURNING id,name,kind,required,config`,[id,projectId,body.name.trim(),body.kind.trim(),body.required!==false,JSON.stringify(body.config??{})]);return {gate:rows[0]};});
 app.get('/api/v1/deployments/:deploymentId/inspector',async(req,reply)=>{const u=await requireUser(req,reply);if(!u)return;const id=String((req.params as any).deploymentId);const r=await pool.query(`SELECT d.id,d.status,d.source_ref AS "sourceRef",d.image,d.container_id AS "containerId",d.url,d.error,d.previous_deployment_id AS "previousDeploymentId",d.created_at AS "createdAt",d.updated_at AS "updatedAt",s.id AS "serviceId",s.name AS "serviceName",s.type,e.id AS "environmentId",e.name AS environment,p.id AS "projectId",p.name AS project FROM deployments d JOIN services s ON s.id=d.service_id JOIN environments e ON e.id=s.environment_id JOIN projects p ON p.id=e.project_id JOIN organization_members om ON om.organization_id=p.organization_id WHERE d.id=$1 AND om.user_id=$2 LIMIT 1`,[id,u.id]);if(!r.rows[0])return reply.code(404).send({error:'Deployment not found'});const [events,gates,comments]=await Promise.all([pool.query('SELECT id,phase,message,metadata,created_at AS "createdAt" FROM deployment_events WHERE deployment_id=$1 ORDER BY created_at',[id]),pool.query('SELECT name,status,message,created_at AS "createdAt",updated_at AS "updatedAt" FROM release_gate_results WHERE deployment_id=$1 ORDER BY created_at',[id]),pool.query('SELECT c.id,c.body,c.created_at AS "createdAt",u.name,u.email FROM deployment_comments c LEFT JOIN users u ON u.id=c.user_id WHERE c.deployment_id=$1 ORDER BY c.created_at',[id])]);return {...r.rows[0],events:events.rows,gates:gates.rows,comments:comments.rows,traffic:{mode:'generation-safe',activeGeneration:r.rows[0].status==='HEALTHY'?id:null},health:{status:r.rows[0].status==='HEALTHY'?'healthy':r.rows[0].status.toLowerCase()}};});
 app.post('/api/v1/deployments/:deploymentId/comments',async(req,reply)=>{const u=await requireUser(req,reply);if(!u)return;const deploymentId=String((req.params as any).deploymentId);const body=req.body as {body?:string};if(!body.body?.trim())return reply.code(400).send({error:'body is required'});const access=await pool.query('SELECT d.id,p.organization_id FROM deployments d JOIN projects p ON p.id=d.project_id JOIN organization_members om ON om.organization_id=p.organization_id WHERE d.id=$1 AND om.user_id=$2 LIMIT 1',[deploymentId,u.id]);if(!access.rows[0])return reply.code(404).send({error:'Deployment not found'});const {rows}=await pool.query('INSERT INTO deployment_comments(id,deployment_id,user_id,body) VALUES($1,$2,$3,$4) RETURNING id,body,created_at AS "createdAt"',[randomUUID(),deploymentId,u.id,body.body.trim()]);return reply.code(201).send(rows[0]);});
 app.get('/api/v1/projects/:projectId/preview-policy',async(req,reply)=>{const u=await requireUser(req,reply);if(!u)return;const id=String((req.params as any).projectId);if(!await projectAccess(id,u.id))return reply.code(404).send({error:'Project not found'});const {rows}=await pool.query('SELECT mode,require_auth AS "requireAuth",expires_hours AS "expiresHours",updated_at AS "updatedAt" FROM preview_policies WHERE project_id=$1',[id]);return {policy:rows[0]??{mode:'team',requireAuth:false,expiresHours:72}};});
 app.put('/api/v1/projects/:projectId/preview-policy',async(req,reply)=>{const u=await requireUser(req,reply);if(!u)return;const id=String((req.params as any).projectId);const access=await projectAccess(id,u.id);if(!access)return reply.code(404).send({error:'Project not found'});const b=req.body as {mode?:string;requireAuth?:boolean;expiresHours?:number};if(!['public','team','protected'].includes(b.mode??''))return reply.code(400).send({error:'mode must be public, team or protected'});const {rows}=await pool.query(`INSERT INTO preview_policies(project_id,mode,require_auth,expires_hours) VALUES($1,$2,$3,$4) ON CONFLICT(project_id) DO UPDATE SET mode=EXCLUDED.mode,require_auth=EXCLUDED.require_auth,expires_hours=EXCLUDED.expires_hours,updated_at=NOW() RETURNING mode,require_auth AS "requireAuth",expires_hours AS "expiresHours"`,[id,b.mode,b.requireAuth===true,Math.min(720,Math.max(1,Number(b.expiresHours??72)))]);return {policy:rows[0]};});
 app.get('/api/v1/projects/:projectId/metrics',async(req,reply)=>{const u=await requireUser(req,reply);if(!u)return;const id=String((req.params as any).projectId);const access=await projectAccess(id,u.id);if(!access)return reply.code(404).send({error:'Project not found'});const [usage,deployments,incidents]=await Promise.all([pool.query(`SELECT metric,unit,COALESCE(SUM(quantity),0) quantity,COUNT(*) samples FROM usage_events WHERE project_id=$1 GROUP BY metric,unit ORDER BY metric`,[id]),pool.query(`SELECT status,COUNT(*) count FROM deployments d JOIN services s ON s.id=d.service_id JOIN environments e ON e.id=s.environment_id WHERE e.project_id=$1 GROUP BY status ORDER BY status`,[id]),pool.query('SELECT severity,status,COUNT(*) count FROM incidents WHERE project_id=$1 GROUP BY severity,status ORDER BY severity',[id])]);return {usage:usage.rows,deployments:deployments.rows,incidents:incidents.rows,generatedAt:new Date().toISOString()};});
 app.get('/api/v1/projects/:projectId/billing',async(req,reply)=>{const u=await requireUser(req,reply);if(!u)return;const id=String((req.params as any).projectId);const access=await projectAccess(id,u.id);if(!access)return reply.code(404).send({error:'Project not found'});const {rows}=await pool.query(`SELECT metric,unit,SUM(quantity) quantity FROM usage_events WHERE project_id=$1 AND recorded_at>=date_trunc('month',NOW()) GROUP BY metric,unit ORDER BY metric`,[id]);return {currency:'USD',estimatedTotal:0,providerMeteringRequired:true,usage:rows};});
 app.get('/api/v1/projects/:projectId/settings',async(req,reply)=>{const u=await requireUser(req,reply);if(!u)return;const id=String((req.params as any).projectId);if(!await projectAccess(id,u.id))return reply.code(404).send({error:'Project not found'});const {rows}=await pool.query('SELECT settings,updated_at AS "updatedAt" FROM project_settings WHERE project_id=$1',[id]);return {settings:rows[0]?.settings??{deployment:{strategy:'rolling',zeroDowntime:true,rollbackOnFailure:true},build:{cache:true},security:{requireReleaseGates:false}}};});
 app.put('/api/v1/projects/:projectId/settings',async(req,reply)=>{const u=await requireUser(req,reply);if(!u)return;const id=String((req.params as any).projectId);const access=await projectAccess(id,u.id);if(!access)return reply.code(404).send({error:'Project not found'});const {rows}=await pool.query(`INSERT INTO project_settings(project_id,settings) VALUES($1,$2) ON CONFLICT(project_id) DO UPDATE SET settings=EXCLUDED.settings,updated_at=NOW() RETURNING settings,updated_at AS "updatedAt"`,[id,JSON.stringify(req.body??{})]);return rows[0];});
 app.get('/api/v1/providers/catalog',async(req,reply)=>{const u=await requireUser(req,reply);if(!u)return;const {rows}=await pool.query('SELECT id,name,category,description,capabilities,enabled FROM provider_catalog WHERE enabled=true ORDER BY category,name');return {providers:rows};});
}
