import type {FastifyInstance} from 'fastify';
import {randomUUID} from 'node:crypto';
import pg from 'pg';
import {userFromToken} from './auth.js';
const {Pool}=pg; const pool=new Pool({connectionString:process.env.DATABASE_URL??'postgres://nexus:nexus_dev_only@127.0.0.1:5432/nexus'});
function session(req:any){return String(req.headers.cookie??'').split(';').map((x:string)=>x.trim()).find((x:string)=>x.startsWith('nexus_session='))?.slice(14)}
async function auth(req:any,reply:any){const u=await userFromToken(session(req));if(!u){reply.code(401).send({error:'Authentication required'});return}return u}
export async function registerPreviewRoutes(app:FastifyInstance){
 app.post('/api/v1/projects/:projectId/previews',async(req,reply)=>{const u=await auth(req,reply);if(!u)return;const {projectId}=req.params as any;const body=req.body as any;const access=await pool.query(`SELECT p.id,p.organization_id FROM projects p JOIN organization_members om ON om.organization_id=p.organization_id WHERE p.id=$1 AND om.user_id=$2`,[projectId,(u as any).id]);if(!access.rowCount)return reply.code(404).send({error:'Project not found'});const slug=`pr-${String(body.number??'preview').replace(/[^a-z0-9-]/gi,'-').toLowerCase()}-${Date.now().toString(36)}`;const id=randomUUID();await pool.query(`INSERT INTO environments(id,project_id,name,slug) VALUES($1,$2,$3,$4)`,[id,projectId,`Preview ${body.number??''}`.trim(),slug]);await pool.query(`INSERT INTO audit_logs(id,organization_id,user_id,action,resource_type,resource_id,metadata) VALUES(gen_random_uuid(),$1,$2,'preview.created','environment',$3,$4)`,[access.rows[0].organization_id,(u as any).id,id,JSON.stringify({pullRequest:body.number??null,commit:body.commit??null})]);return reply.code(201).send({id,projectId,name:`Preview ${body.number??''}`.trim(),slug,expiresAt:new Date(Date.now()+1000*60*60*24*7).toISOString()})});
 app.delete('/api/v1/environments/:environmentId/previews',async(req,reply)=>{const u=await auth(req,reply);if(!u)return;const {environmentId}=req.params as any;const r=await pool.query(`DELETE FROM environments e USING projects p,organization_members om WHERE e.id=$1 AND e.project_id=p.id AND om.organization_id=p.organization_id AND om.user_id=$2 RETURNING e.id`,[environmentId,(u as any).id]);if(!r.rowCount)return reply.code(404).send({error:'Preview environment not found'});return {deleted:true,id:environmentId}});
}
