import pg from 'pg';
import { randomUUID } from 'node:crypto';
import { addDeploymentEvent, getDeploymentState, listDeployments } from './db.js';
import type { FastifyInstance } from 'fastify';
const { Pool } = pg;
const pool = new Pool({ connectionString: process.env.DATABASE_URL ?? 'postgres://nexus:nexus_dev_only@127.0.0.1:5432/nexus' });
type GateConfig={id:string;name:string;kind:string;required:boolean;config:any};
type GateResult={name:string;kind:string;required:boolean;status:'passed'|'failed'|'skipped';message:string};
const normalize=(v:string)=>v.toLowerCase().replace(/[- ]/g,'_');
async function configs(projectId:string):Promise<GateConfig[]>{return (await pool.query('SELECT id,name,kind,required,config FROM release_gate_configs WHERE project_id=$1 ORDER BY created_at',[projectId])).rows;}
async function ensureResult(deploymentId:string,gate:GateConfig,result:GateResult){await pool.query(`INSERT INTO release_gate_results(id,deployment_id,gate_id,name,status,message) VALUES($1,$2,$3,$4,$5,$6) ON CONFLICT(deployment_id,name) DO UPDATE SET status=EXCLUDED.status,message=EXCLUDED.message,updated_at=NOW()`,[randomUUID(),deploymentId,gate.id,gate.name,result.status,result.message]);}
async function runOne(deploymentId:string,gate:GateConfig,ctx:any):Promise<GateResult>{const kind=normalize(gate.kind);try{
if(kind==='env_validation'||kind==='environment'){const required=Array.isArray(gate.config?.required)?gate.config.required:[];const missing=required.filter((key:string)=>ctx.env?.[key]===undefined&&process.env[key]===undefined);return missing.length?{name:gate.name,kind:gate.kind,required:gate.required,status:'failed',message:`Missing required environment values: ${missing.join(', ')}`}:{name:gate.name,kind:gate.kind,required:gate.required,status:'passed',message:'Required environment values are present'};}
if(kind==='build')return{name:gate.name,kind:gate.kind,required:gate.required,status:ctx.built?'passed':'skipped',message:ctx.built?'Build completed successfully':'Build gate is evaluated after the build stage'};
if(kind==='security'||kind==='security_scan'){const findings=Array.isArray(ctx.securityFindings)?ctx.securityFindings:[];return findings.length?{name:gate.name,kind:gate.kind,required:gate.required,status:'failed',message:`Security gate found ${findings.length} blocking finding(s)`}:{name:gate.name,kind:gate.kind,required:gate.required,status:'passed',message:'No blocking security findings were reported'};}
if(kind==='github_checks'||kind==='github'){if(ctx.githubChecks===undefined)return{name:gate.name,kind:gate.kind,required:gate.required,status:'skipped',message:'GitHub check data is not available for this deployment'};return ctx.githubChecks===true?{name:gate.name,kind:gate.kind,required:gate.required,status:'passed',message:'GitHub checks passed'}:{name:gate.name,kind:gate.kind,required:gate.required,status:'failed',message:'GitHub checks did not pass'};}
if(kind==='health'||kind==='smoke'){if(!ctx.url)return{name:gate.name,kind:gate.kind,required:gate.required,status:'skipped',message:'Runtime URL is not available yet'};const response=await fetch(ctx.url,{signal:AbortSignal.timeout(Number(gate.config?.timeoutMs??5000)),redirect:'manual'});const expected=Array.isArray(gate.config?.expectedStatuses)?gate.config.expectedStatuses:[200];const ok=expected.includes(response.status);return{name:gate.name,kind:gate.kind,required:gate.required,status:ok?'passed':'failed',message:ok?`Runtime responded with HTTP ${response.status}`:`Expected ${expected.join(', ')} but runtime returned HTTP ${response.status}`};}
if(kind==='approval'||kind==='human_approval')return{name:gate.name,kind:gate.kind,required:gate.required,status:'failed',message:'Deployment requires an explicit approval before release'};
return{name:gate.name,kind:gate.kind,required:gate.required,status:'skipped',message:`Gate kind '${gate.kind}' is not executable yet`};
}catch(error){return{name:gate.name,kind:gate.kind,required:gate.required,status:'failed',message:String(error)};}}
export async function runPreReleaseGates(projectId:string,deploymentId:string,ctx:any){const gates=await configs(projectId);const results:GateResult[]=[];for(const gate of gates){const kind=normalize(gate.kind);if(kind==='build'||kind==='health'||kind==='smoke')continue;const result=await runOne(deploymentId,gate,ctx);results.push(result);await ensureResult(deploymentId,gate,result);await addDeploymentEvent(deploymentId,'RELEASE_GATE',`${gate.name}: ${result.status} — ${result.message}`,{gate:gate.name,kind:gate.kind,required:gate.required});}const blocking=results.filter(r=>r.required&&r.status==='failed');if(blocking.length)throw new Error(`Required release gate failed: ${blocking.map(r=>r.name).join(', ')}`);return results;}
export async function runPostReleaseGates(projectId:string,deploymentId:string,ctx:any){const gates=await configs(projectId);const results:GateResult[]=[];for(const gate of gates){const kind=normalize(gate.kind);if(kind!=='build'&&kind!=='health'&&kind!=='smoke')continue;const result=kind==='build'?{name:gate.name,kind:gate.kind,required:gate.required,status:ctx.built?'passed':'failed',message:ctx.built?'Build completed successfully':'Build did not complete'} as GateResult:await runOne(deploymentId,gate,ctx);results.push(result);await ensureResult(deploymentId,gate,result);await addDeploymentEvent(deploymentId,'RELEASE_GATE',`${gate.name}: ${result.status} — ${result.message}`,{gate:gate.name,kind:gate.kind,required:gate.required});}const blocking=results.filter(r=>r.required&&r.status==='failed');if(blocking.length)throw new Error(`Required post-release gate failed: ${blocking.map(r=>r.name).join(', ')}`);return results;}
export function registerReleaseGateLifecycle(app:FastifyInstance){app.addHook('onRoute',(route:any)=>{if(route.method!=='POST'||route.url!=='/api/v1/deployments'||typeof route.handler!=='function')return;const original=route.handler;route.handler=async function(this:any,request:any,reply:any){const body=request.body as any;const deploymentId=String(body?.id??'');if(deploymentId&&body?.projectId){await runPreReleaseGates(String(body.projectId),deploymentId,{env:body.env??{}});}const result=await original.call(this,request,reply);const accepted=result?.accepted&&result?.id?result:null;if(accepted){void (async()=>{for(let attempt=0;attempt<60;attempt++){await new Promise(r=>setTimeout(r,2000));try{const deployment=(await listDeployments()).find((d:any)=>d.id===accepted.id) as any;const state=await getDeploymentState(accepted.id);if(!deployment)break;if(deployment.status==='failed'){await runPostReleaseGates(String(accepted.projectId),accepted.id,{built:false});break;}if(deployment.status==='ready'||state?.phase==='LIVE'){const url=deployment.runtime?.url??deployment.runtime?.publicUrl??deployment.runtime?.endpoint??deployment.runtime?.address;await runPostReleaseGates(String(accepted.projectId),accepted.id,{built:Boolean(deployment.repo?deployment.runtime:deployment.runtime),url});break;}}catch(error){await addDeploymentEvent(accepted.id,'RELEASE_GATE',`Post-release gate runner error: ${String(error)}`,{error:String(error)});break;}}})()}return result;};});}
