import type { FastifyInstance } from 'fastify';
import { createCipheriv, createHash, createHmac, randomBytes, randomUUID, timingSafeEqual } from 'node:crypto';
import pg from 'pg';
import { userFromToken } from './auth.js';
import { registerProductionPlatformRoutes } from './production-platform-routes.js';
const { Pool }=pg;
const pool=new Pool({connectionString:process.env.DATABASE_URL??'postgres://nexus:nexus_dev_only@127.0.0.1:5432/nexus'});
const engine=()=>process.env.ENGINE_URL??'http://localhost:4100';
const token=(req:any)=>{const raw=String(req.headers.cookie??'');for(const p of raw.split(';')){const [k,...v]=p.trim().split('=');if(k==='nexus_session')return decodeURIComponent(v.join('='));}return undefined;};
async function user(req:any,reply:any){const u=await userFromToken(token(req));if(!u){reply.code(401).send({error:'Authentication required'});return undefined;}return u as {id:string};}
function key(){const raw=process.env.SECRETS_ENCRYPTION_KEY;if(process.env.NODE_ENV==='production'&&!raw)throw new Error('SECRETS_ENCRYPTION_KEY is required in production');return createHash('sha256').update(raw??process.env.AUTH_SECRET??'change-this-secret').digest();}
function encrypt(value:string){const iv=randomBytes(12);const c=createCipheriv('aes-256-gcm',key(),iv);const body=Buffer.concat([c.update(value,'utf8'),c.final()]);return `${iv.toString('base64url')}.${c.getAuthTag().toString('base64url')}.${body.toString('base64url')}`;}
function internalSecret(){const secret=process.env.ENGINE_INTERNAL_SECRET;if(!secret)throw new Error('ENGINE_INTERNAL_SECRET is required');return createHmac('sha256',secret).update('nexus-engine').digest('hex');}
function validInternal(req:any){const supplied=req.headers['x-engine-secret']?.toString();const expected=process.env.ENGINE_INTERNAL_SECRET?internalSecret():'';if(!supplied||!expected||supplied.length!==expected.length)return false;return timingSafeEqual(Buffer.from(supplied),Buffer.from(expected));}
async function accessService(serviceId:string,userId:string){const q=await pool.query(`SELECT s.id,s.name,s.type,e.id AS environment_id,p.id AS project_id,p.organization_id FROM services s JOIN environments e ON e.id=s.environment_id JOIN projects p ON p.id=e.project_id JOIN organization_members om ON om.organization_id=p.organization_id WHERE s.id=$1 AND om.user_id=$2 LIMIT 1`,[serviceId,userId]);return q.rows[0];}
export type DeploymentNode={id:string;name:string;endpoint:string;region:string};
export async function selectDeploymentNode(cpuMillis=100,memoryBytes=128*1024*1024,preferredRegion?:string):Promise<DeploymentNode|undefined>{const {rows}=await pool.query(`SELECT id,name,endpoint,region,status,capacity_cpu_millis AS "capacityCpuMillis",used_cpu_millis AS "usedCpuMillis",capacity_memory_bytes AS "capacityMemoryBytes",used_memory_bytes AS "usedMemoryBytes" FROM runtime_nodes WHERE status <> 'offline' AND (last_heartbeat_at IS NULL OR last_heartbeat_at > NOW() - INTERVAL '45 seconds')`);const candidates=rows.filter((n:any)=>n.status==='online'&&n.endpoint&&Number(n.capacityCpuMillis)-Number(n.usedCpuMillis)>=cpuMillis&&Number(n.capacityMemoryBytes)-Number(n.usedMemoryBytes)>=memoryBytes);candidates.sort((a:any,b:any)=>{const ar=preferredRegion&&a.region===preferredRegion?0:1;const br=preferredRegion&&b.region===preferredRegion?0:1;if(ar!==br)return ar-br;return (Number(a.usedCpuMillis)/Number(a.capacityCpuMillis)+Number(a.usedMemoryBytes)/Number(a.capacityMemoryBytes))-(Number(b.usedCpuMillis)/Number(b.capacityCpuMillis)+Number(b.usedMemoryBytes)/Number(b.capacityMemoryBytes));});const n=candidates[0];return n?{id:String(n.id),name:String(n.name),endpoint:String(n.endpoint),region:String(n.region)}:undefined;}
export async function registerRuntimePlatformRoutes(app:FastifyInstance){
app.get('/api/v1/runtime/nodes',async(req,reply)=>{const u=await user(req,reply);if(!u)return;const {rows}=await pool.query(`SELECT id,name,endpoint,region,capacity_cpu_millis AS "capacityCpuMillis",capacity_memory_bytes AS "capacityMemoryBytes",used_cpu_millis AS "usedCpuMillis",used_memory_bytes AS "usedMemoryBytes",status,last_heartbeat_at AS "lastHeartbeatAt" FROM runtime_nodes ORDER BY region,name`);return {nodes:rows};});
app.post('/api/v1/runtime/nodes',async(req,reply)=>{const u=await user(req,reply);if(!u)return;const body=req.body as any;if(!body.name||!body.endpoint)return reply.code(400).send({error:'name and endpoint are required'});const id=randomUUID();await pool.query(`INSERT INTO runtime_nodes(id,name,endpoint,region,capacity_cpu_millis,capacity_memory_bytes) VALUES($1,$2,$3,$4,$5,$6) ON CONFLICT(name) DO UPDATE SET endpoint=EXCLUDED.endpoint,region=EXCLUDED.region,capacity_cpu_millis=EXCLUDED.capacity_cpu_millis,capacity_memory_bytes=EXCLUDED.capacity_memory_bytes,status='online',last_heartbeat_at=NOW()`,[id,String(body.name),String(body.endpoint),String(body.region||'local'),Number(body.capacityCpuMillis||1000),Number(body.capacityMemoryBytes||1073741824)]);return reply.code(202).send({accepted:true,name:body.name});});
app.post('/api/v1/runtime/nodes/:name/heartbeat',async(req,reply)=>{if(!validInternal(req))return reply.code(401).send({error:'Unauthorized node heartbeat'});const body=req.body as any;const result=await pool.query(`UPDATE runtime_nodes SET status='online',last_heartbeat_at=NOW(),used_cpu_millis=GREATEST(0,$2),used_memory_bytes=GREATEST(0,$3) WHERE name=$1`,[String((req.params as any).name),Number(body.usedCpuMillis||0),Number(body.usedMemoryBytes||0)]);if(!result.rowCount)return reply.code(404).send({error:'Node not found'});return {ok:true};});
app.post('/api/v1/services/:serviceId/managed-data',async(req,reply)=>{const u=await user(req,reply);if(!u)return;const service=await accessService(String((req.params as any).serviceId),u.id);if(!service)return reply.code(404).send({error:'Service not found'});if(!['database','redis'].includes(service.type))return reply.code(400).send({error:'Service must be database or redis'});const body=req.body as any;const dataEngine=service.type==='database'?'postgres':'redis';const instanceId=randomUUID();const r=await fetch(`${engine()}/api/v1/managed-data/provision`,{method:'POST',headers:{'content-type':'application/json','x-engine-secret':internalSecret()},body:JSON.stringify({instanceId,engine:dataEngine,version:body.version,name:service.name})});const result=await r.json() as any;if(!r.ok)return reply.code(502).send({error:'Managed data provisioning failed',detail:result});const secretId=randomUUID();await pool.query(`INSERT INTO secrets(id,environment_id,service_id,name,encrypted_value) VALUES($1,$2,$3,$4,$5)`,[secretId,service.environment_id,service.id,'DATABASE_URL',encrypt(String(result.connectionUri))]);await pool.query(`INSERT INTO database_instances(id,service_id,engine,version,connection_uri_secret_id,status,endpoint,container_name) VALUES($1,$2,$3,$4,$5,'ready',$6,$7)`,[instanceId,service.id,dataEngine,body.version||null,secretId,result.endpoint,result.containerName]);await pool.query(`UPDATE services SET config=config || $2::jsonb WHERE id=$1`,[service.id,JSON.stringify({managed:true,instanceId,nodeName:result.nodeName})]);return reply.code(201).send({id:instanceId,serviceId:service.id,engine:dataEngine,status:'ready',endpoint:result.endpoint,containerName:result.containerName,nodeName:result.nodeName});});
app.get('/api/v1/services/:serviceId/managed-data',async(req,reply)=>{const u=await user(req,reply);if(!u)return;const service=await accessService(String((req.params as any).serviceId),u.id);if(!service)return reply.code(404).send({error:'Service not found'});const {rows}=await pool.query(`SELECT id,engine,version,status,endpoint,container_name AS "containerName",created_at AS "createdAt",updated_at AS "updatedAt" FROM database_instances WHERE service_id=$1 ORDER BY created_at DESC`,[service.id]);return {instances:rows};});
await registerProductionPlatformRoutes(app);
}
