'use client';

import { useEffect, useState } from 'react';
import { ArrowLeft, CheckCircle2, GitBranch, LockKeyhole, RefreshCw, ShieldCheck, Activity, Boxes } from 'lucide-react';

const API = '/api/nexus';
type Project={id:string;name:string;repo?:string};
type Gate={id:string;name:string;kind:string;required:boolean;config:Record<string,unknown>};
type Policy={mode:string;requireAuth:boolean;expiresHours:number};
type Provider={id:string;name:string;category:string;description:string;capabilities:string[]};
type Metrics={deployments:{status:string;count:string}[];incidents:{severity:string;status:string;count:string}[];usage:{metric:string;unit:string;quantity:string}[]};

async function request<T>(path:string,init?:RequestInit):Promise<T>{
 const r=await fetch(`${API}${path}`,{...init,credentials:'include',headers:{...(init?.body?{'content-type':'application/json'}:{}),...(init?.headers??{})}});
 const v=await r.json().catch(()=>({}));
 if(!r.ok) throw new Error(v.error||v.detail||`Request failed (${r.status})`);
 return v as T;
}

export default function ReleaseSafetyPage(){
 const [projects,setProjects]=useState<Project[]>([]),[projectId,setProjectId]=useState(''),[gates,setGates]=useState<Gate[]>([]),[policy,setPolicy]=useState<Policy|null>(null),[metrics,setMetrics]=useState<Metrics|null>(null),[providers,setProviders]=useState<Provider[]>([]),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);
 const [gateName,setGateName]=useState('Production health'),[gateKind,setGateKind]=useState('health'),[required,setRequired]=useState(true);
 async function loadProjects(){try{const v=await request<{projects:Project[]}>('/v1/platform/overview');setProjects(v.projects);if(!projectId&&v.projects[0])setProjectId(v.projects[0].id);}catch(e){setMessage(e instanceof Error?e.message:'Unable to load projects')}}
 async function load(){if(!projectId)return;setBusy(true);try{const [g,p,m,pc]=await Promise.all([request<{gates:Gate[]}>(`/v1/projects/${projectId}/release-gates`),request<{policy:Policy}>(`/v1/projects/${projectId}/preview-policy`),request<Metrics>(`/v1/projects/${projectId}/metrics`),request<{providers:Provider[]}>('/v1/providers/catalog')]);setGates(g.gates);setPolicy(p.policy);setMetrics(m);setProviders(pc.providers);}catch(e){setMessage(e instanceof Error?e.message:'Unable to load release controls')}finally{setBusy(false)}}
 useEffect(()=>{loadProjects()},[]);useEffect(()=>{load()},[projectId]);
 async function saveGate(){if(!projectId||!gateName.trim())return;setBusy(true);try{const v=await request<{gate:Gate}>(`/v1/projects/${projectId}/release-gates`,{method:'PUT',body:JSON.stringify({name:gateName.trim(),kind:gateKind,required,config:{}})});setGates(x=>{const rest=x.filter(g=>g.name!==v.gate.name);return [...rest,v.gate]});setMessage(`Release gate “${v.gate.name}” saved.`)}catch(e){setMessage(e instanceof Error?e.message:'Gate update failed')}finally{setBusy(false)}}
 async function savePolicy(mode:string){if(!projectId)return;setBusy(true);try{const v=await request<{policy:Policy}>(`/v1/projects/${projectId}/preview-policy`,{method:'PUT',body:JSON.stringify({mode,requireAuth:mode!=='public',expiresHours:72})});setPolicy(v.policy);setMessage(`Preview protection set to ${mode}.`)}catch(e){setMessage(e instanceof Error?e.message:'Preview policy update failed')}finally{setBusy(false)}}
 return <main className="platformPage"><header className="platformHeader"><div><a href="/platform" className="backLink"><ArrowLeft size={15}/> Control plane</a><span className="eyebrow">NEXUS / RELEASE SAFETY</span><h1>Release safety center</h1><p>One place for release gates, preview protection, deployment signals and runtime capabilities.</p></div><button className="mini" onClick={load}><RefreshCw size={15}/> Refresh</button></header>
 {message&&<div className="platformNotice"><CheckCircle2 size={17}/><span>{message}</span><button onClick={()=>setMessage('')}>×</button></div>}
 <section className="platformCard full"><div className="cardHead"><div><span className="eyebrow">PROJECT</span><h2>Release target</h2></div><GitBranch size={19}/></div><select className="wideSelect" value={projectId} onChange={e=>setProjectId(e.target.value)}><option value="">Select project…</option>{projects.map(p=><option key={p.id} value={p.id}>{p.name}{p.repo?` · ${p.repo}`:''}</option>)}</select></section>
 <section className="platformGrid"><article className="platformCard"><div className="cardHead"><div><span className="eyebrow">GATES</span><h2>Release gates</h2></div><ShieldCheck size={19}/></div><p className="muted">Required checks are recorded before a production rollout. Configure one or more gates per project.</p><div className="table">{gates.map(g=><div className="platformRow" key={g.id}><span><b>{g.name}</b><small>{g.kind} · {g.required?'required':'advisory'}</small></span><span className="pill">configured</span></div>)}{!gates.length&&<p className="empty">No project gates configured yet.</p>}</div><div className="releaseForm"><input value={gateName} onChange={e=>setGateName(e.target.value)} placeholder="Gate name"/><select value={gateKind} onChange={e=>setGateKind(e.target.value)}><option value="build">Build</option><option value="security">Security scan</option><option value="health">Health</option><option value="smoke">Smoke test</option><option value="checks">GitHub checks</option><option value="approval">Human approval</option></select><label><input type="checkbox" checked={required} onChange={e=>setRequired(e.target.checked)}/> Required</label><button className="deployAction" disabled={busy||!projectId} onClick={saveGate}>Save gate</button></div></article>
 <article className="platformCard"><div className="cardHead"><div><span className="eyebrow">PREVIEWS</span><h2>Preview protection</h2></div><LockKeyhole size={19}/></div><p className="muted">Control who can access isolated deployment URLs and how long preview access remains valid.</p><div className="policyGrid">{['public','team','protected'].map(mode=><button key={mode} className={`policyOption ${policy?.mode===mode?'selected':''}`} disabled={busy||!projectId} onClick={()=>savePolicy(mode)}><b>{mode}</b><span>{mode==='public'?'Anyone with the URL':mode==='team'?'Organization members':'Protected access'}</span></button>)}</div><div className="securityCallout"><LockKeyhole size={20}/><div><b>{policy?.requireAuth?'Authentication required':'Public preview'}</b><span>Expiration: {policy?.expiresHours??72} hours.</span></div></div></article></section>
 <section className="platformGrid"><article className="platformCard"><div className="cardHead"><div><span className="eyebrow">SIGNALS</span><h2>Project health</h2></div><Activity size={19}/></div><div className="usageGrid">{(metrics?.deployments??[]).slice(0,4).map(x=><div key={x.status}><b>{x.count}</b><span>{x.status} deployments</span></div>)}</div><div className="table">{(metrics?.incidents??[]).map(x=><div className="platformRow" key={`${x.severity}-${x.status}`}><span><b>{x.severity}</b><small>{x.status}</small></span><span className="pill">{x.count}</span></div>)}{!metrics?.incidents.length&&<p className="empty">No incident signals recorded.</p>}</div></article>
 <article className="platformCard"><div className="cardHead"><div><span className="eyebrow">RUNTIME</span><h2>Provider capabilities</h2></div><Boxes size={19}/></div><div className="table">{providers.map(p=><div className="platformRow" key={p.id}><span><b>{p.name}</b><small>{p.category} · {p.description}</small></span><span className="pill">{p.capabilities?.slice(0,2).join(' · ')}</span></div>)}</div></article></section>
 </main>
}
