'use client';

import { useEffect, useMemo, useState } from 'react';
import { Activity, ArrowLeft, Box, CheckCircle2, Cloud, Database, KeyRound, Layers3, Plus, RefreshCw, ShieldCheck, Terminal, Trash2, Wallet, X } from 'lucide-react';

const API = '/api/nexus';
type Project = { id: string; name: string; repo?: string; organizationId?: string; createdAt?: string };
type Overview = { organizations: { id: string; name: string; slug: string; role: string }[]; projects: Project[]; services: { id: string; name: string; type: string; environment: string; project: string }[]; deployments: { id: string; status: string; project: string; createdAt: string }[] };
type Token = { id: string; name: string; scopes: string[]; expiresAt?: string | null; createdAt: string; lastUsedAt?: string | null };
type Audit = { id: string; action: string; resourceType: string; resourceId: string; metadata: unknown; createdAt: string; email?: string };
type Environment = { id: string; projectId: string; name: string; slug: string };
type Service = { id: string; environmentId: string; name: string; type: string };

async function request<T>(path: string, init?: RequestInit): Promise<T> {
  const r = await fetch(`${API}${path}`, { ...init, credentials: 'include', headers: { ...(init?.body ? { 'content-type': 'application/json' } : {}), ...(init?.headers ?? {}) } });
  const v = await r.json().catch(() => ({}));
  if (!r.ok) throw new Error(v.detail || v.error || `Request failed (${r.status})`);
  return v as T;
}

const cards = [
  ['Environments', 'Production, staging and isolated preview targets.', Layers3],
  ['Secrets', 'Encrypted environment values with audit trails.', KeyRound],
  ['Services', 'Web, worker, cron, private, database and Redis workloads.', Box],
  ['Release safety', 'Health-gated deployments and recovery controls.', ShieldCheck],
  ['Observability', 'Deployment state, activity and operational history.', Activity],
  ['Portable runtime', 'Provider-neutral nodes and Docker-backed execution.', Cloud],
] as const;

export default function PlatformPage() {
  const [overview, setOverview] = useState<Overview | null>(null), [tokens, setTokens] = useState<Token[]>([]), [audit, setAudit] = useState<Audit[]>([]), [environments, setEnvironments] = useState<Environment[]>([]), [services, setServices] = useState<Service[]>([]);
  const [projectId, setProjectId] = useState(''), [environmentId, setEnvironmentId] = useState(''), [tab, setTab] = useState('control'), [message, setMessage] = useState(''), [busy, setBusy] = useState(false), [modal, setModal] = useState<string | null>(null);
  const [name, setName] = useState(''), [serviceName, setServiceName] = useState('api'), [serviceType, setServiceType] = useState('web'), [secretName, setSecretName] = useState(''), [secretValue, setSecretValue] = useState(''), [tokenName, setTokenName] = useState('ci-deploy');
  const project = useMemo(() => overview?.projects.find(p => p.id === projectId), [overview, projectId]);
  const selectedEnvironment = environments.find(e => e.id === environmentId);

  async function load() { try { const [o,t,a] = await Promise.all([request<Overview>('/v1/platform/overview'), request<{tokens:Token[]}>('/v1/tokens'), request<{audit:Audit[]}>('/v1/audit?limit=50')]); setOverview(o); setTokens(t.tokens); setAudit(a.audit); if (!projectId && o.projects[0]) setProjectId(o.projects[0].id); } catch(e) { setMessage(e instanceof Error ? e.message : 'Unable to load control plane'); } }
  async function loadEnvironments(id:string) { if(!id)return; try { const v=await request<{environments:Environment[]}>(`/v1/projects/${id}/environments`); setEnvironments(v.environments); } catch { setEnvironments([]); } }
  async function loadServices(id:string) { if(!id)return; try { const v=await request<{services:Service[]}>(`/v1/environments/${id}/services`); setServices(v.services); } catch { setServices([]); } }
  useEffect(()=>{load();},[]); useEffect(()=>{loadEnvironments(projectId);},[projectId]); useEffect(()=>{loadServices(environmentId);},[environmentId]);

  async function createEnvironment(){if(!projectId||!name.trim())return setMessage('Select a project and enter an environment name.');setBusy(true);try{const v=await request<Environment>(`/v1/projects/${projectId}/environments`,{method:'POST',body:JSON.stringify({name:name.trim()})});setEnvironments(x=>[v,...x]);setEnvironmentId(v.id);setName('');setModal(null);setMessage(`Environment ${v.name} created.`);}catch(e){setMessage(e instanceof Error?e.message:'Environment creation failed')}finally{setBusy(false)}}
  async function createService(){if(!environmentId||!serviceName.trim())return setMessage('Select an environment and enter a service name.');setBusy(true);try{const v=await request<Service>(`/v1/environments/${environmentId}/services`,{method:'POST',body:JSON.stringify({name:serviceName.trim(),type:serviceType,source:{},config:{}})});setServices(x=>[v,...x]);setModal(null);setMessage(`Service ${v.name} created.`);}catch(e){setMessage(e instanceof Error?e.message:'Service creation failed')}finally{setBusy(false)}}
  async function saveSecret(){if(!environmentId||!secretName.trim()||!secretValue)return setMessage('Select an environment and provide a secret name and value.');setBusy(true);try{await request(`/v1/environments/${environmentId}/secrets/${encodeURIComponent(secretName.trim())}`,{method:'PUT',body:JSON.stringify({value:secretValue})});setModal(null);setSecretValue('');setMessage(`Secret ${secretName.trim()} encrypted and saved.`);await load();}catch(e){setMessage(e instanceof Error?e.message:'Secret update failed')}finally{setBusy(false)}}
  async function createToken(){if(!tokenName.trim())return setMessage('Enter a token name.');setBusy(true);try{const v=await request<Token&{token:string}>('/v1/tokens',{method:'POST',body:JSON.stringify({name:tokenName.trim(),scopes:['platform:read','deployments:write']})});setTokens(x=>[v,...x]);setModal(null);setMessage(`Token created. Copy it now: ${v.token}`);}catch(e){setMessage(e instanceof Error?e.message:'Token creation failed')}finally{setBusy(false)}}
  async function revokeToken(id:string){if(!confirm('Revoke this API token?'))return;try{await request(`/v1/tokens/${id}`,{method:'DELETE'});setTokens(x=>x.filter(t=>t.id!==id));setMessage('API token revoked.')}catch(e){setMessage(e instanceof Error?e.message:'Token revocation failed')}}

  const tabs=[['control','Control plane'],['environments','Environments'],['services','Services'],['secrets','Secrets'],['tokens','API tokens'],['audit','Audit log'],['usage','Usage & cost']];
  return <main className="platformPage"><header className="platformHeader"><div><a href="/" className="backLink"><ArrowLeft size={15}/> Console</a><span className="eyebrow">NEXUS / PLATFORM</span><h1>Infrastructure control plane</h1><p>Vercel-level developer experience with Nexus application graphs, portable runtimes and recovery-first releases.</p></div><button className="mini" onClick={()=>{load();if(projectId)loadEnvironments(projectId)}}><RefreshCw size={15}/> Refresh</button></header>
    {message&&<div className="platformNotice"><CheckCircle2 size={17}/><span>{message}</span><button onClick={()=>setMessage('')}><X size={14}/></button></div>}
    <div className="platformTabs">{tabs.map(([id,label])=><button key={id} className={tab===id?'active':''} onClick={()=>setTab(id)}>{label}</button>)}</div>
    {tab==='control'&&<><div className="featureGrid">{cards.map(([title,text,Icon])=><article className="featureCard" key={title}><Icon size={19}/><b>{title}</b><span>{text}</span></article>)}</div><section className="platformGrid"><Panel title="Projects" eyebrow="WORKSPACE" count={overview?.projects.length??0}>{overview?.projects.map(p=><button className={`platformRow ${projectId===p.id?'selected':''}`} key={p.id} onClick={()=>setProjectId(p.id)}><span><b>{p.name}</b><small>{p.repo||'No repository linked'}</small></span><span>›</span></button>)}</Panel><Panel title="Services" eyebrow="RUNTIME" count={overview?.services.length??0}>{overview?.services.slice(0,8).map(s=><div className="platformRow" key={s.id}><span><b>{s.name}</b><small>{s.type} · {s.environment} · {s.project}</small></span><span className="pill">{s.type}</span></div>)}</Panel><Panel title="Deployments" eyebrow="RELEASES" count={overview?.deployments.length??0}>{overview?.deployments.slice(0,8).map(d=><div className="platformRow" key={d.id}><span><b>{d.project}</b><small>{d.id.slice(0,8)} · {new Date(d.createdAt).toLocaleString()}</small></span><span className={`pill ${d.status.toLowerCase()}`}>{d.status}</span></div>)}</Panel></section><section className="quickActions"><b>Quick actions</b><button onClick={()=>setModal('environment')}><Plus size={15}/> Environment</button><button disabled={!environmentId} onClick={()=>setModal('service')}><Plus size={15}/> Service</button><button disabled={!environmentId} onClick={()=>setModal('secret')}><KeyRound size={15}/> Secret</button><button onClick={()=>setModal('token')}><Terminal size={15}/> API token</button><a href="/deploy"><Plus size={15}/> Deployment</a></section></>}
    {tab==='environments'&&<Resource title="Environments" eyebrow="ISOLATED RELEASE TARGETS" action="New environment" onAction={()=>setModal('environment')}><select className="wideSelect" value={projectId} onChange={e=>setProjectId(e.target.value)}><option value="">Select project…</option>{overview?.projects.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select><div className="table">{environments.map(e=><button className={`platformRow ${environmentId===e.id?'selected':''}`} key={e.id} onClick={()=>setEnvironmentId(e.id)}><span><b>{e.name}</b><small>{e.slug} · {e.id}</small></span><span className="pill">{e.name.toLowerCase().includes('prod')?'production':'isolated'}</span></button>)}{!environments.length&&<p className="empty">No environments yet. Create production, staging or preview targets.</p>}</div></Resource>}
    {tab==='services'&&<Resource title="Service catalog" eyebrow="APPLICATION GRAPH" action="New service" onAction={()=>setModal('service')}><p className="muted">{selectedEnvironment?`Managing ${project?.name||'project'} / ${selectedEnvironment.name}.`:'Select an environment first.'}</p><div className="table">{services.map(s=><div className="platformRow" key={s.id}><span><b>{s.name}</b><small>{s.type} · {s.id}</small></span><span className="pill">{s.type}</span></div>)}{!services.length&&<p className="empty">No services in this environment.</p>}</div></Resource>}
    {tab==='secrets'&&<Resource title="Secrets" eyebrow="ENCRYPTED CONFIGURATION" action="Add secret" onAction={()=>setModal('secret')}><div className="securityCallout"><ShieldCheck size={22}/><div><b>Write-only secret storage</b><span>Values are encrypted at rest and never returned in plaintext. Updates create audit events.</span></div></div><p className="muted">Environment: {selectedEnvironment?.name||'select an environment'}</p></Resource>}
    {tab==='tokens'&&<Resource title="API tokens" eyebrow="AUTOMATION" action="Create token" onAction={()=>setModal('token')}><p className="muted">Scoped credentials for CI/CD and the Nexus CLI. Tokens are hashed at rest and shown once.</p><div className="table">{tokens.map(t=><div className="platformRow" key={t.id}><span><b>{t.name}</b><small>{t.scopes.join(' · ')} · created {new Date(t.createdAt).toLocaleDateString()}</small></span><button className="iconButton" onClick={()=>revokeToken(t.id)} title="Revoke"><Trash2 size={15}/></button></div>)}{!tokens.length&&<p className="empty">No tokens created.</p>}</div></Resource>}
    {tab==='audit'&&<Resource title="Audit log" eyebrow="SECURITY HISTORY"><p className="muted">Sensitive control-plane operations recorded for your organization.</p><div className="table">{audit.map(a=><div className="platformRow" key={a.id}><span><b>{a.action}</b><small>{a.resourceType}:{a.resourceId} · {a.email||'system'} · {new Date(a.createdAt).toLocaleString()}</small></span><span className="pill">recorded</span></div>)}{!audit.length&&<p className="empty">No audit events.</p>}</div></Resource>}
    {tab==='usage'&&<Resource title="Usage & cost" eyebrow="COST CONTROL"><div className="usageGrid"><div><b>{overview?.deployments.length??0}</b><span>tracked deployments</span></div><div><b>{overview?.services.length??0}</b><span>service records</span></div><div><b>{tokens.length}</b><span>automation tokens</span></div><div><b>{audit.length}</b><span>recent audit events</span></div></div><div className="securityCallout"><Wallet size={22}/><div><b>Provider-aware billing boundary</b><span>Nexus records usage events but does not invent provider prices. Monetary billing requires connected provider metering.</span></div></div></Resource>}
    {modal&&<div className="modalBackdrop"><div className="deployModal platformModal"><div className="modalHead"><div><span className="eyebrow">NEXUS CONTROL PLANE</span><h2>{modal==='environment'?'Create environment':modal==='service'?'Create service':modal==='secret'?'Add encrypted secret':'Create API token'}</h2></div><button className="close" onClick={()=>setModal(null)}><X size={17}/></button></div>{modal==='environment'&&<><label>Environment name<input value={name} onChange={e=>setName(e.target.value)} placeholder="staging"/></label><button className="deployAction" disabled={busy} onClick={createEnvironment}>{busy?'Creating…':'Create environment'}</button></>}{modal==='service'&&<><label>Service name<input value={serviceName} onChange={e=>setServiceName(e.target.value)} placeholder="api"/></label><label>Service type<select value={serviceType} onChange={e=>setServiceType(e.target.value)}>{['web','worker','cron','private','database','redis'].map(v=><option key={v}>{v}</option>)}</select></label><button className="deployAction" disabled={busy||!environmentId} onClick={createService}>{busy?'Creating…':'Create service'}</button></>}{modal==='secret'&&<><label>Secret name<input value={secretName} onChange={e=>setSecretName(e.target.value)} placeholder="DATABASE_URL"/></label><label>Secret value<input type="password" value={secretValue} onChange={e=>setSecretValue(e.target.value)} placeholder="••••••••" autoComplete="new-password"/></label><button className="deployAction" disabled={busy||!environmentId} onClick={saveSecret}>{busy?'Encrypting…':'Save encrypted secret'}</button></>}{modal==='token'&&<><label>Token name<input value={tokenName} onChange={e=>setTokenName(e.target.value)} placeholder="ci-deploy"/></label><div className="modalNote">The token is shown only once. Store it in GitHub Actions or another CI secret manager.</div><button className="deployAction" disabled={busy} onClick={createToken}>{busy?'Creating…':'Create token'}</button></>}</div></div>}
  </main>;
}
function Panel({title,eyebrow,count,children}:{title:string;eyebrow:string;count:number;children:React.ReactNode}){return <article className="platformCard"><div className="cardHead"><div><span className="eyebrow">{eyebrow}</span><h2>{title}</h2></div><span>{count}</span></div>{children}</article>}
function Resource({title,eyebrow,action,onAction,children}:{title:string;eyebrow:string;action?:string;onAction?:()=>void;children:React.ReactNode}){return <section className="platformCard full"><div className="cardHead"><div><span className="eyebrow">{eyebrow}</span><h2>{title}</h2></div>{action&&<button className="mini" onClick={onAction}><Plus size={14}/>{action}</button>}</div>{children}</section>}
